<?php
   $title ="developers - libdvbpsi";
   require($_SERVER["DOCUMENT_ROOT"]."/include/header.php");
?>

<h1 class="bigtitle">libdvbpsi</h1>

<p> <code>libdvbpsi</code> is a simple library designed for decoding and
generation of MPEG TS and DVB PSI tables. </p>

<p> Currently supported platforms are GNU/Linux, Windows and Mac OS X, but it
should work on almost any platform. </p>

<h2>Current features</h2>

<ul class="bullets">
  <li> Program Association Table (PAT), decoder and generator. </li>
  <li> Program Map Table (PMT), decoder and generator. </li>
  <li> All MPEG 2 descriptors, decoders and generators. </li>
</ul>

<h2>Get libdvbpsi</h2>

<p> <code>libdvbpsi</code> is available through <a href="http://wiki.videolan.org/Subversion">Subversion</a> or
by browsing the <a href="http://www.videolan.org/pub/libdvbpsi/">releases</a>.
</p>

<p> You can also see the <a href="libdvbpsi/ChangeLog.html">ChangeLog</a>.</p>

<h2>Documentation</h2>

<table border="0">
<tr>
  <td class="type"><b>Document</b></td>
  <td class="type"><b>Status</b></td>
  <td class="type"><b>Download</b></td>
  <td class="type"><b>Maintainer</b></td>
</tr>

<tr>
  <td class="category">Libdvbpsi API documentation</td>
   <td class="yes">
     Up-to-date
   </td>
  <td>
     <a href="libdvbpsi/doc/doxygen/html/">HTML</a>
     <a href="libdvbpsi/doc/doxygen/latex/refman.dvi">DVI</a>
     <a href="libdvbpsi/doc/doxygen/latex/refman.ps">PS</a>
   </td>
   <td>
     Generated by Doxygen
   </td>
</tr>

</table>

<?php footer('$Id$'); ?>
