<div style="text-align: center"><a href="/"><img border=0 src="/images/cone-soppera10-moyen.png" alt="life is a cone" /></a></div>
<br />
<br />

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu>Projects</th></tr>
<tr><td class=menu>
<p class=menu><a class="menu" href="/vlc/">VLC media player</a></p>
<p class=menu><a class="menu" href="/vls/">VLS</a></p>
<p class=menu><a class="menu" href="/libdvdcss/">libdvdcss</a></p>
<p class=menu><a class="menu" href="/libdvdplay/">libdvdplay</a></p>
<p class=menu><a class="menu" href="/libdvbpsi/">libdvbpsi</a></p>
<p class=menu><a class="menu" href="http://www.videolan.org/dtsdec.html/">libdts</a></p>
<p class=menu><a class="menu" href="http://www.videolan.org/x264.html/">x264</a></p>
</td></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu>Resources</th></tr>
<tr><td class=menu>
<p class=menu><a class="menu" href="/svn.html">Subversion</a></p>
<p class=menu><a class="menu" href="/cvs.html">CVS</a></p>
<p class=menu><a class="menu" href="/lists.html">Mailing lists</a></p>
<p class=menu><a class="menu"
href="http://bugzilla.videolan.org/">Bugzilla</a></p>
<p class=menu><a class="menu"
href="http://developers.videolan.org/cgi-bin/viewcvs.cgi/">ViewCVS</a></p>
<p class=menu><a class="menu"
href="http://www.videolan.org/cgi-bin/irc/irc.cgi">IRCWeb</a></p>
</td></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu>Links</th></tr>
<tr><td class=menu>
<p class=menu><a class="menu" href="http://www.videolan.org/">http://www.videolan.org/</a></p>
<p class=menu><a class="menu" href="http://forum.videolan.org/">http://forum.videolan.org/</a></p>
</td></tr>
</table>
<br>

