<a href="/"><img border=0 src="/images/cone.png" alt="life
is a cone" /></a>
<br />
<br />

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu><a class="menu" href="http://www.videolan.org/">User
site</a></th></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu>Resources</th></tr>
<tr><td class=menu>
<p class=menu><a class="menu" href="/cvs.html">CVS</a></p>
<p class=menu><a class="menu" href="/lists.html">Mailing lists</a></p>
<p class=menu><a class="menu"
href="http://bugzilla.videolan.org/">Bugzilla</a></p>
<p class=menu><a class="menu"
href="http://www.videolan.org/cgi-bin/cvsweb/">CVSWeb</a></p>
<p class=menu><a class="menu"
href="http://www.videolan.org/cgi-bin/irc/irc.cgi">IRCWeb</a></p>
</td></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu>Developer doc</th></tr>
<tr><td class=menu>
<p class=menu><a class="menu" href="/vlc/devel_doc.html">vlc</a></p>
<p class=menu><a class="menu" href="/vls/devel_doc.html">vls</a></p>
<p class=menu><a class="menu" href="/libdvdcss/devel_doc.html">libdvdcss</a></p>
<p class=menu><a class="menu" href="/libdvbpsi/devel_doc.html">libdvbpsi</a></p>
</td></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu>ChangeLog</th></tr>
<tr><td class=menu>
<p class=menu><a class="menu" href="/vlc/ChangeLog.html">vlc</a></p>
<p class=menu><a class="menu" href="/vls/ChangeLog.html">vls</a></p>
<p class=menu><a class="menu" href="/libdvdcss/ChangeLog.html">libdvdcss</a></p>
<p class=menu><a class="menu" href="/libdvdplay/ChangeLog.html">libdvdplay</a></p>
<p class=menu><a class="menu" href="/libdvbpsi/ChangeLog.html">libdvbpsi</a></p>
</td></tr>
</table>
<br>

