<a href="/"><img border=0 src="/images/cone.png" alt="life
is a cone" /></a>
<br />
<br />

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu>VideoLAN Client</th></tr>
<tr><td class=menu>
<p class=menu><a href="/vlc/ChangeLog">Changelog</a></p>
<p class=menu><a href="/">Developer doc</a></p>
</td></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu>VideoLAN Server</th></tr>
<tr><td class=menu>
<p class=menu><a href="/vls/ChangeLog">Changelog</a></p>
<p class=menu><a href="/">Developer doc</a></p>
</td></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu>libdvdcss</th></tr>
<tr><td class=menu>
<p class=menu><a href="/libdvdcss/ChangeLog">Changelog</a></p>
<p class=menu><a href="/">Developer doc</a></p>
</td></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu>libdvbpsi</th></tr>
<tr><td class=menu>
<p class=menu><a href="/libdvbpsi/ChangeLog">Changelog</a></p>
<p class=menu><a href="/">Developer doc</a></p>
</td></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu>Resources</th></tr>
<tr><td class=menu>
<p class=menu><a href="/cvs.html">CVS</a></p>
<p class=menu><a href="/lists.html">Mailing lists</a></p>
<p class=menu><a
href="http://bugzilla.videolan.org/">Bugzilla</a></p>
<p class=menu><a
href="http://www.videolan.org/cgi-bin/cvsweb/">CVSWeb</a></p>
<p class=menu><a
href="http://www.videolan.org/cgi-bin/irc/irc.cgi">IRCWeb</a></p>
<p class=menu><a href="http://www.videolan.org/">User site</a></p>
</td></tr>
</table>
<br>

