<div style="text-align: center"><a href="/"><img width="73" height="100" border=0 src="/images/cone-soppera7-moyen.png" alt="life is a cone" /></a></div>
<br />
<br />

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu><a class="menu" href="http://www.videolan.org/">User
site</a></th></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu>Resources</th></tr>
<tr><td class=menu>
<p class=menu><a class="menu" href="/cvs.html">CVS</a></p>
<p class=menu><a class="menu" href="/lists.html">Mailing lists</a></p>
<p class=menu><a class="menu"
href="http://bugzilla.videolan.org/">Bugzilla</a></p>
<p class=menu><a class="menu"
href="http://www.videolan.org/cgi-bin/cvsweb/">CVSWeb</a></p>
<p class=menu><a class="menu"
href="http://www.videolan.org/cgi-bin/irc/irc.cgi">IRCWeb</a></p>
</td></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu>VLC</th></tr>
<tr><td class=menu>
<p class=menu><a class="menu" href="/vlc/devel_doc.html">developer doc</a></p>
<p class=menu><a class="menu" href="/vlc/ChangeLog.html">ChangeLog</a></p>
</td></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu>VLS</th></tr>
<tr><td class=menu>
<p class=menu><a class="menu" href="/vls/devel_doc.html">developer doc</a></p>
<p class=menu><a class="menu" href="/vls/ChangeLog.html">ChangeLog</a></p>
</td></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu><a class="menu" href="/libdvdcss/index.html">libdvdcss</a></th></tr>
<tr><td class=menu>
<p class=menu><a class="menu" href="/libdvdcss/ChangeLog.html">ChangeLog</a></p>
<p class=menu><a class="menu" href="/pub/videolan/libdvdcss/">download</a></p>
<p class=menu><a class="menu" href="/libdvdcss/devel_doc.html">developer doc</a></p>
</td></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu><a class="menu" href="/libdvdplay/index.html">libdvdplay</a></th></tr>
<tr><td class=menu>
<p class=menu><a class="menu" href="/libdvdplay/ChangeLog.html">ChangeLog</a></p>
<p class=menu><a class="menu" href="/pub/videolan/libdvdplay/">download</a></p>
</td></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class=menu><a class="menu" href="/libdvbpsi/index.html">libdvbpsi</a></th></tr>
<tr><td class=menu>
<p class=menu><a class="menu" href="/pub/videolan/libdvbpsi/">download</a></p>
<p class=menu><a class="menu" href="/libdvbpsi/ChangeLog.html">ChangeLog</a></p>
<p class=menu><a class="menu" href="/libdvbpsi/devel_doc.html">developer doc</a></p>
</td></tr>
</table>
<br>


