<div style="text-align: center"><a href="/"><img border=0 src="/images/cone-soppera10-moyen.png" alt="life is a cone" /></a></div>
<br />
<br />

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class="menu">Projects</th></tr>
<tr><td class="menu">
<p class="menu"><a class="menu" href="/vlc/">VLC media player</a></p>
<p class="menu"><a class="menu" href="/vls/">VLS</a></p>
<p class="menu"><a class="menu" href="/libdvdcss/">libdvdcss</a></p>
<p class="menu"><a class="menu" href="/libdvdplay/">libdvdplay</a></p>
<p class="menu"><a class="menu" href="/libdvbpsi/">libdvbpsi</a></p>
<p class="menu"><a class="menu" href="/libdca.html">libdca</a></p>
<p class="menu"><a class="menu" href="/x264.html">x264</a></p>
</td></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class="menu">Resources</th></tr>
<tr><td class="menu">
<p class="menu"><a class="menu" href="/svn.html">Subversion</a></p>
<p class="menu"><a class="menu" href="/lists.html">Mailing lists</a></p>
<p class="menu"><a class="menu" href="https://trac.videolan.org/">Trac - project management</a></p>
<!--<p class="menu"><a class="menu"
href="http://bugzilla.videolan.org/">Bugzilla</a></p>-->
<p class="menu"><a class="menu"
href="http://krishna.videolan.org/cgi-bin/irc/irc.cgi">IRCWeb</a></p>
</td></tr>
</table>
<br>

<table width="100%" cellspacing=0 cellpadding=0>
<tr><th class="menu">Links</th></tr>
<tr><td class="menu">
<p class="menu"><a class="menu" href="http://www.videolan.org/">The VideoLAN Website</a></p>
<p class="menu"><a class="menu" href="http://forum.videolan.org/">The VideoLAN Forums</a></p>
<p class="menu"><a class="menu" href="http://wiki.videolan.org/">The VideoLAN Wiki</a></p>
<p class="menu"><a class="menu" href="http://nightlies.videolan.org/">VLC nightly builds and source snapshots</a></p>
</td></tr>
</table>
<br>

