# Les commentaires commencent par un # en premier position 
# Et les nouveaux topics par un "|" (Attention donc au découpage!!
#

|17 Jan 2004| OSI Merit Award| The VideoLAN project is very proud
to announce that it has been awarded with an Open Source Merit Award
by the <a href="http://www.opensource.org">Open Source
Initiative</a>. We are very glad to be honored in this
way and will continue to strive to making the project, VLC media player
and VLS, the best programs out there.<br />
You can read more about the award in these <a href="http://builder.com.com"
>builder.com</a> articles: <a href="http://builder.com.com/5100-6375-5136758.html">
article 1</a> <a href="http://builder.com.com/5100-6375-5136135.html">
article 2</a>.

|10 Jan 2004| Release: VLS 0.5.5| This release of VLS fixes a bug
introduced in the DVB input of the previous release. Go to the <a
href="http://www.videolan.org/streaming/download-vls-sources.html">VLS
source code download page</a> to get this new version now !

|3 Jan 2004| Release: VLC 0.7.0| This major release of VLC Media
Player, codenamed "Bond", features major core enhancements, support
for RTP/RTSP, new audio visual effects, supports for new formats
(Speex, MPEG2 4/2/2, AAC+SBR, ...), many interfaces and playlist
enhancements, a new interface for MacOS X, a DirectShowinput on
Win32, support for MacOS X 10.3 Panther, and much more! Look <a
href="http://developers.videolan.org/vlc/NEWS">here</a> for a complete
list of changes. To download the sources or the binary package of this
new version, go to the <a href="http://www.videolan.org/vlc/">VLC
download page</a> and click on your OS logo!<br />
<b>Attention: </b>The first version of the OS X package didn't include
the Flac decoder. If you experience problems with Flac audio, please
download again.

|2 Jan 2004| Release: libdvbpsi 0.1.4| This new release of libdvbpsi 
fixes a few bugs and adds support for DVB subtitles descriptor

|1 Jan 2004| Happy new year| The VideoLAN team wishes you a happy new
year !

|29-30 Dec 2003| Scheduled downtime| Due to a power audit, major
disruptions are expected. A rescue line will be set up during the
downtime, but due to a very narrow bandwidth, only the main website 
will be (partially) up. Sorry for the inconvenience.

|13 Dec 2003| Release: miniSAPserver 0.2.3| This new release
fixes an IPv6 bug, adds support for HTTP streams and for the
SLP announcing protocol. It also uses the recent playlist group
system of VLC (requires CVS or beta version of VLC). You can <a
href="http://www.videolan.org/streaming/download-sap-server.html">download
 the sources</a> for this release.

|28 Nov 2003| Release: VLS 0.5.4 | This new release
of the VideoLAN Server fixes two major bugs:
the "program_number don't match" bug (read <a
href="http://www.via.ecp.fr/via/ml/vls-devel/200311/msg00012.html">this</a>
for more explanations about this fix) and a bug in the RTP
option that made VLS consume unnecessary resources. Go to the <a
href="http://www.videolan.org/streaming/download-vls-sources.html">VLS
source code download page</a> to get this new version now !

|23 Nov 2003| New web forum for VideoLAN| The VideoLAN team
is pleased to announce the opening of our new webforum (<a
href="http://forum.videolan.org">http://forum.videolan.org</a>). We hope
this will help improve user support, communication between VideoLAN
users, and sharing of ideas. Have fun !

|31 Oct - 1 Nov 2003| 5th Free software days in Lyons| VideoLAN
will be present at the 5th Free Software (<i>Journées du Libre</i>)
in Lyons, France. We will have a demo of the streaming solution
on our booth ! For more information about the event, see the <a
href="http://www.aldil.org/agenda/journees/2003/">ALDIL web site</a>.

|20 Oct 2003| VideoLAN doc switches to GPL| Due to legal problems with
the GNU FDL license, the VideoLAN doc was switched to General Public
License. The VideoLAN Quickstart was also removed, as it was redundant
with the VideoLAN Howto.

|20 Sept 2003| VLC awarded by MacGeneration| During Apple Expo
Paris 2003, VLC won the trophy for developers support ! For more
details about the MacGeneration 2003 Trophies, please see <a
href="http://www.macgeneration.com/mgnews/depeche.php?aIdDepeche=103478"
>this news</a> (French, see <a href="http://babelfish.altavista.com/babelfish/urlload?url=http%3A%2F%2Fwww.macgeneration.com%2Fmgnews%2Fdepeche.php%3FaIdDepeche%3D103478&lp=fr_en&tt=url">BabelFish</a> for an English translation).

|14 Aug 2003| Release: VLC 0.6.2| This new release of VLC follows
the previous one very closely because it mainly fixes a regression in
VLC 0.6.1 which made some streams unplayable. VLC 0.6.2 also features
an improved MPEG TS muxer, proper PTS/DTS generation in the transcoding
module, support for DVB-S/C/T cards using V4L2 API, DVD menus navigation
in the wxWindows interface and fixes to the VCD navigation. Look <a
href="http://developers.videolan.org/vlc/NEWS">here</a> for a complete
list of changes. To download the sources or the binary packages of
this new version, go to the <a href="http://www.videolan.org/vlc/">VLC
download page</a> and click on your OS logo!

|31 July 2003| Release: VLC 0.6.1| This new release of VLC media
player features: vorbis and mp3 audio support for the transcoding
module, improved HTTP remote control interface, improved support
for the Matroska container format, new subtitle module which
uses freetype2 to render arbitrary fonts in any size, improved
PS muxer (it can create MPEG-1 files now and produce streams
with system headers), Windows fixes (DVD support, 5.1 audio for
sblive/audigy and sound on NT4), improved ALSA support and a new
GTK2 interface for the "Linux on PDA" distributions! Look <a
href="http://developers.videolan.org/vlc/NEWS">here</a> for a complete
list of changes. To download the sources or the binary packages of
this new version, go to the <a href="http://www.videolan.org/vlc/">VLC
download page</a> and click on your OS logo! WARNING: the first version
of the Mac OS X package was broken... so if you have problems under Mac
OS X, download the package again!

|29 July 2003| Release: libdvdcss 1.2.8 & libdvbpsi 0.1.3| Libdvdcss
1.2.8 is a bug-fix release with a fix for encrypted DVDs on Windows
and a workaround for strange discs that report read errors seemingly
at random. Libdvbpsi 0.1.3 features new DVB descriptors decoders and
generators, a new SDT decoder and various fixes and enhancements. Go to
the <a href="http://developers.videolan.org/libdvdcss/">libdvdcss</a>
and <a href="http://developers.videolan.org/libdvbpsi/">libdvbpsi</a>
web pages to read the Changelog and download the sources or the Debian
packages.

|25 July 2003| Release: miniSAPserver 0.2.2| Minor bug fix of the
miniSAPserver. Remember miniSAPserver should be used to announce the
streams sent by VLS; the streams sent by VLC's stream output can be
announced by VLC itself !

|25 June 2003| VLC runner up for Apple Design Award| VLC 0.5.3 is
runner up for Apple Design Award 2003. You can see the trophy on the
<a href="/events/">events page</a>.

|23 June 2003| Release: VLC 0.6.0| This major release of VLC
media player features a new Video 4 Linux input, a new CDDA
input, multicast IPv6 support under Windows and Mac OS X, support
for Sorenson 3, a new HTTP remote control interface, improved
wxWindows and skin interfaces (now available for X11), a new stream
output scheme with transcoding support and much more! Look <a
href="http://developers.videolan.org/vlc/NEWS">here</a> for a complete
list of changes. To download the sources or the binary packages of
this new version, go to the <a href="http://www.videolan.org/vlc/">VLC
download page</a> and click on your OS logo!

|23 June 2003| Release: Libdvdcss 1.2.7| This new release of
libdvdcss, a DVD decryption library used by VLC and many other GPL media
players, has key caching enabled by default and some bugfixes. See the <a
href="http://developers.videolan.org/libdvdcss/">libdvdcss page</a> to
download the sources or the Debian packages.

|20 June 2003| Release: miniSAPserver 0.2.1| This new version of the
miniSAPserver offers IPv6 support both for announces and announced
streams, together with the CVS version of VLC.

|16 June 2003| VideoLAN Wiki opened | We have set up a Wiki 
(ie, a website that everyone can change) at 
<a href="http://wiki.videolan.org">http://wiki.videolan.org</a>. Its 
goal is to document what is not in the official documentation: the tips
for each O.S, the graphical interfaces, ... We hope that the 
contribution of VideoLAN users will help us keep a documentation 
as up-to-date as possible.

|11-13 June 2003| Renater IPv6 conference| The VideoLAN team has a booth
at the <a href="http://www.renater.fr/IPv6-2003Caen/index.htm">Renater
IPv6 conference</a> that takes place at the University of Caen
(France). There is a running demo of IPv6 streaming with VideoLAN in
unicast and multicast at the booth!

|10 June 2003| Documentation update | The VLS user guide is back and
we have a Spanish translation of the VideoLAN FAQ by Javier Varela
: see the <a href="/doc/">documentation page</a>. All the VideoLAN
documentation is now in Docbook XML.

|6 June 2003| Release: VLS 0.5.3 | This release fixes a bug in the
command line parsing, adds DVD title and chapter selection with the
configuration file and features a new Windows installer.

|29 May 2003| Hauppauge WinTV-PVR-250 supported | We have managed to
stream from a Hauppauge WinTV-PVR-250 (an MPEG-2 encoding card) under
Linux ! It gives much better results than the Visiontech Kfir card. The
chapter "Stream from an MPEG encoding card" of the VideoLAN HOWTO has
been updated, see the <a href="/doc/">documentation page</a>.

|26 May 2003| Release: mini-SAP-server 0.2.0 | This new release of the
mini-SAP-server produces packets that should be conform to the RFC and
adds a "port" option. Only the CVS version of VLC accepts its announces.

|25 May 2003| VLC FAQ becomes VideoLAN FAQ | The new VideoLAN FAQ is
available in multiple formats on the <a href="/doc/">documentation
page</a>. If you have remarks about it or would like new questions to be
integrated in it, post in one of the user mailing-lists.

|23 May 2003| VLC nominated at the Free Software
Trophies! | VLC was nominated at the <a
href="http://www.tropheesdulibre.org/main.php?lang=en">Free Software
Trophies</a>, an international competition aimed at promoting the
development of free software, in the category "General Public".

|21 May 2003| Release: VLS 0.5.2 | This release fixes a bug when
trying to stream multiple DVB channels and a bug in the configure
script with DVB drivers. To download this new version, go to the <a
href="http://www.videolan.org/streaming/">streaming page</a>.

|16 May 2003| Release: VLS 0.5.1 | VLS for Windows is back ! The Windows
port of VLS has been fixed. This new version also features the loop
on broken PS files and setting the TTL under Windows. To download the
sources or the Windows executable of this new version, go to the <a
href="http://www.videolan.org/streaming/">streaming page</a>.

|26 Apr 2003| New VideoLAN HOWTO | The new VideoLAN HOWTO is now
complete and up-to-date. The chapter about the channel information
service now explains how to do SAP/SDP announces with the new <a
href="/streaming/download-sap-server.html">mini-SAP-server</a>. See the
<a href="/doc/">documentation page</a> and report any problem to the
<a href="/support/lists.html">user mailing-lists</a>.

|8 Apr 2003| Release: VLC 0.5.3 | This new release features the
first steps towards skinable interfaces (only on Windows, not
yet on Mac OS X or *nix). Support for playing directories and
video4linux are other big new features. Many bugs have been fixed,
including the problem with USB speakers on MacOS X. Look <a
href="http://developers.videolan.org/vlc/NEWS">here</a> for a complete
list of changes. To download the sources or the binary packages of
this new version, go to the <a href="http://www.videolan.org/vlc/">VLC
download page</a> and click on your OS logo!

|8 Apr 2003| New skin for the Web site | Karibu has designed a new skin
for the Web site : enjoy !

|21 Mar 2003| VIA and VideoLAN annual presentation day| The VIA
and VideoLAN teams are pleased to invite you to their annual
presentation day at the Ecole Centrale Paris (Châtenay-Malabry,
France). There will be a presentation of VideoLAN in French at
10:45 a.m. with a full demonstration. If you are interested, please
visit <a href="http://www.via.ecp.fr/via/journeevia2003.html">this
page</a>. To receive an invitation, send a mail to <a
href="mailto:journee2003@via.ecp.fr">journee2003@via.ecp.fr</a>.

|11 Mar 2003| Release: VLC 0.5.2 | This new release features
improved audio quality (especially under Mac OS X), support for
new audio formats (audio DV and FLAC), support for streaming of
DivX 1/2/3, WMV 1/2 and h/i263 with VLC's stream output and many
bug fixes (including the lock-ups under Mac OS X). To download the
sources or the binary packages of this new version, go to the <a
href="http://www.videolan.org/vlc/">VLC download page</a> and click on
your OS logo!

|11 Mar 2003| Release: VLS 0.5.0 | This major release features a
new command line interface, support for the new LinuxTV drivers
(which brings support for the streaming of digital terrestial
television channels), MPEG-4 TS support and many bug fixes. Because
of a well hidden bug, VLS is not available under Windows any
more. To download the sources of this new version, go to the <a
href="http://www.videolan.org/streaming/">streaming page</a>.

|10 Mar 2003| Release: libdvdcss 1.2.6 | This is a bug
fix release of libdvdcss, a DVD decryption library used
by VLC and many other GPL media players. See the <a
href="http://developers.videolan.org/libdvdcss/">libdvdcss page</a> to
download the sources or the binaires.

|10 Mar 2003| Release: libdvdplay 1.0.1 | This is a bug fix release
of libdvdplay, a DVD navigation library used by VLC. See the <a
href="http://developers.videolan.org/libdvdplay/">libdvdplay page</a> to
download the sources or the binaires.

|26 Feb 2003| Release: vlc for YOPY| The VideoLAN team is proud
to announce that vlc now works on YOPY/Linupy based PDAs !
Please have a look at the <a href="/vlc/download-linupy.html">
download page</a>.

|18 Feb 2003| Release: vlc 0.5.1a for Mac OS X | This is a bug-fix
release of VLC for Mac OS X only: It fixes the problem with 
VLC starting up in a different language than your preferred 
language and an issue with sound missing on several files
that previously worked perfectly. Download the new version of VLC 
for Mac OS X <a href="/vlc/download-macosx.html">here</a>.

|17 Feb 2003| Release: vlc 0.5.1 | This is a bug-fix
release of VLC with a few new features : see the <a
href="http://developers.videolan.org/vlc/NEWS">list of changes between
0.5.0 and 0.5.1</a> and go to the <a href="/vlc/">VLC section</a>
of the website to download the binaries for your OS or the sources.
Unfortunately, this release doesn't fix the audio problems under Mac OS
X... but VideoLAN developers are working hard on it !

|3 Feb 2003| Release: vlc 0.5.0 | This is a major release
of VLC with a a lot of great new features : see the <a
href="http://developers.videolan.org/vlc/NEWS">list of changes between
0.4.6 and 0.5.0</a> and go to the <a href="/vlc/">VLC section</a>
of the website to download the binaries for your OS or the sources.
A new VLC user guide has been released (it replaces the VLC HOWTO)
and the VideoLAN Quickstart has been updated to explain the new
streaming capacity of VLC (with VLC's new stream output) : see the <a
href="/doc/">documentation page</a>.

|3 Feb 2003| Release: libdvdplay 1.0.0 | This is the first release
of libdvdplay, a DVD navigation library. This library is based on a
lot of Ogle's code and features basic read and seek for DVD media,
export of the DVD information (audio, subtitles, chapters, ...) and
export of the DVD virtual machine to the client application. See the <a
href="http://developers.videolan.org/libdvdplay/">libdvdplay page</a> to
download the sources or the binaires.

|3 Feb 2003| Release: libdvdcss 1.2.5 | This new libdvdcss release
adds key cache support, improves robustness in case of read errors
and builds under Cygwin and Microsoft Visual C++. See the <a
href="http://developers.videolan.org/libdvdcss/">libdvdcss page</a> to
download the sources or the binaires.

|29 Jan 2003| VideoLAN at Linux Expo Paris | VideoLAN will have a booth
at <a href="http://www.linuxsolutions.fr">Linux Expo Paris 2003</a>
(4-5-6 February 2003 at the CNIT). The VideoLAN team will welcome you at
the booth and invites you to its <a href="http://www.linuxsolutions.fr/EN/home/index.php?site=conferences_programme">conference</a> (Conference n°5, February
5th afternoon).

|19 Jan 2003| New VideoLAN Quickstart | The VideoLAN Quickstart has been
completely rewritten. See the <a href="/doc/">documentation page</a>.

|19 Jan 2003| New web site | Welcome to our new web site:
it was designed to be simpler and more comprehensive for
end-users. There is a separate site for developers: <a
href="http://developers.videolan.org/">developers.videolan.org</a>.
If you find errors, please write to <a
href="mailto:webmaster@videolan.org">webmaster@videolan.org</a>.

|14 Nov 2002| Release: vlc 0.4.6 | This new release uses a52dec as the
default decoder for AC3 sound for a better quality, fixes a hangup in
the esd plugin, allows Windows NT/2000/XP users to read DVDs without
administrator privileges and fixes a few segfaults. Have a look at
the <a href="/vlc/changelog.html">ChangeLog</a> and go to the <a
href="/vlc/download.html">download page</a>.

|14 Nov 2002| Release: libdvdcss 1.2.4 | This release
allows Windows NT/2000/XP users to watch DVDs with vlc
0.4.6 without administrator privileges. Check the <a
href="/libdvdcss/index.html">libdvdcss</a> page, and have a look at the
<a href="http://videolan.org/libdvdcss/changelog.html">Changelog</a>.

|4 Nov 2002| Pictures and slides of JDL Lyons | The pictures and the
slides of the Free Software Days in Lyons are online: see the <a
href="/events/">events page</a>.

|1-2 Nov 2002| Free Software days in Lyons | VideoLAN will be
present at the Free Software Days (<i>Journées du Libre</i>) in Lyons
(France): four developers will have a stand with a running demo of
VideoLAN. This event is organized by ALDIL, and you will have all the
information about the stands, the conferences and a site map on <a
href="http://www.aldil.org/agenda/journees/2002/">this page</a>.

|14 Oct 2002| Release: vlc 0.4.5 | This new release brings enhancements to
the BeOS and iPAQ familiar Linux ports, as well as a new RTP input. VLC
is also compliant to general practice on how to embed A/52, DVD SPU and
LPCM elementary streams in MPEG-2 TS. It can still read from VLS 0.3.x
with the --vls-backwards-compat option.
Visit the <a href="/vlc/changelog.html">ChangeLog</a> and the <a
href="/vlc/download.html">download page</a>.

|13 Oct 2002| Release: mini-vlcs 0.2.0 | This new release adds
IPv6 support, features unlimited channel numbers and auto-reload
when the configuration file is changed. Get-it from the <a
href="/network/download.html">download page</a>!

|13 Oct 2002| Release: vls 0.4.0 | This new release adds IPv6 multicast
support, language descriptors for audio and subpicture streams, and
support for WinTV DVB-S. It also features an RTP output, runtime adding
of programs and channels, start-up script,
and is compliant to general practice on how
to embed A/52, DVD SPU and LPCM elementary streams. This release
requires VLC version 0.4.5 or later. Get it now from the
<a href="/vls/download.html">download page</a>!

|13 Oct 2002| Release: libdvdcss 1.2.3 | This release fixes many issues
in the Windows port. Check the
<a href="/libdvdcss/index.html">libdvdcss</a> page, and have a look at the <a href="http://videolan.org/libdvdcss/changelog.html">Changelog</a>.

|13 Oct 2002| Release: vlms 0.2.3 | VLMS now generates valid CRCs, and is
compliant to general practice on how to embed A/52, DVD SPU and LPCM elementary
streams. This release requires VLC version 0.4.5 or later.
<a href="/vlms/download.html">Download it now</a>.

|12 Oct 2002| Release: libdvbpsi 0.1.2 | This release fixes miscellaneous
portability issues, and a bug in the PMT generator which created
over-complicated PMTs. Check the
<a href="/libdvbpsi/index.html">libdvbpsi</a> page, and have a look at the <a href="http://videolan.org/libdvbpsi/changelog.html">Changelog</a>.

|11 Aug 2002| Release: vlc 0.4.4 | This release fixes some Windows
bugs and is built on the newest libdvdcss. It also features ffmpeg
AVIs playing. Subtitles should be readable again under MacOS X.
Visit the <a href="/vlc/changelog.html">ChangeLog</a> and the <a
href="/vlc/download.html">download page</a>.

|11 Aug 2002| Release: libdvdcss 1.2.2 | This release fixes the
"ioctl_ReadTitleKey failed" bug reported by RPC2 drives users. Check the
<a href="/libdvdcss/index.html">libdvdcss</a> page, and have a look at the <a href="http://videolan.org/libdvdcss/changelog.html">Changelog</a>.

|26 Jul 2002| Release: vlc 0.4.3 | This release <b>fixes the
QT6 compatibility issue</b> under MacOS X! Also includes a few
BeOS improvements, and several other bugfixes. Visit the <a
href="/vlc/changelog.html">ChangeLog</a> and the <a
href="/vlc/download.html">download page</a>.

|10 Jul 2002| Release: vlc 0.4.2 | This is a small bugfix release, but
also features multicast IPv6 support and new deinterlacing plugins. See
the <a href="/vlc/changelog.html">ChangeLog</a> and the <a
href="/vlc/download.html">download page</a>.

|4 Jun 2002| Release: vlc 0.4.1 | This is mostly a bugfix release
with a few improvements. Support for AVI files with AC3 audio, new
MMX optimizations in the video decoder an improved Win32 interface,
and a lot of other bugfixes. See
full <a href="/vlc/changelog.html">ChangeLog</a> for more
information. Then go to the <a href="/vlc/download.html">download
page</a>.

|4 Jun 2002| Release: vlms 0.2.2 | vlms works
under MacOSX and Solaris and not only under Linux.
Now the playlist and looping options work with TS files.
<a href="/vlms/download.html">Download it now</a>

|2 Jun 2002| Release: libdvdcss 1.2.1 | This release fixes
a bug preventing to read DVDs when the disc's region didn't
match the drive's. Also, QNX support was added. Check the <a
href="/libdvdcss/index.html">libdvdcss</a> page.

|29 May 2002| Tests at Centrale Paris| The VideoLAN Team is
starting today a vast test campaign on the campus of the <a
href="http://www.ecp.fr">Ecole Centrale Paris</a>. We are streaming
13 channels at the same time using multicast on the brand new
network (Gigabit Ethernet backbone and 100 Mbit/s switches on
the periphery from our partner <a href="partners.html">Extreme
Networks</a>) of the <a href="http://www.via.ecp.fr">VIA Centrale
Réseaux</a> association. The students are invited to visit <a
href="tests/">www.videolan.org/tests/</a> for instructions.

|23 May 2002| Release: vlc 0.4.0 | This is a major release which
adds MPEG-4/DivX support and many enhancements for Mac OS X and Windows.
It also fixes dozens of causes of crashes and freezes. See
full <a href="/vlc/changelog.html">ChangeLog</a> for more
information. Then go to the <a href="/vlc/download.html">download
page</a>.

|23 May 2002| Release: libdvdcss 1.2.0 | This release
fixed a grave crash with some DVDs. Check the <a
href="/libdvdcss/index.html">libdvdcss</a> page!

|18 May 2002| Release: libdvbpsi 0.1.1 | This release has full MPEG 2
descriptors decoding and generation capabilities. Get it now from the
<a href="/libdvbpsi/download.html">download page</a>.

|14 May 2002| VideoLAN HOWTO| The <a
href="network/doc/videolan-howto.html">VideoLAN HOWTO</a> explains
how to use the complete VideoLAN solution. It deals in particular
with the different streaming methods (unicast, broadcast,
multicast), the issue of IPv6, the use of channel tools, Video on
Demand and the design of a complete solution. It has been written
by <a href="mailto:marcari@videolan.org">Marc Ariberti</a> and <a
href="mailto:alexis@videolan.org">Alexis de Lattre</a>.|

|14 May 2002| Release: vlms 0.2.1| This release adds a few
convenient options. It is now possible to change the TTL value
and to make the vlms repeat its playlist.|

|13 may 2002| Release: vls 0.3.3 | This new release adds a long
awaited Windows port for the vls! Get it now from the
<a href="/vls/download.html">download page</a>!

|23 apr 2002| Thinkpad received | We eventually received the
IBM Thinkpad as a reward for the IBM Linux Challenge. See
the <a href="events/index.html">events page</a> and the <a
href="events/20020423/index.html">pictures</a> taken during the
unpacking party.

|18 apr 2002| New vlc HOWTO | <a href="mailto:jobi@videolan.org">Jobi</a>
updated the <a href="vlc/doc/vlc-howto.html">vlc HOWTO</a>. It is an
important document for all the users of vlc.

|18 apr 2002| Release: vlc 0.3.1 | This is a bugfix release which
addresses issues discovered in 0.3.0. Lots of crashes fixed, see the
full <a href="/vlc/changelog.html">ChangeLog</a> for more
information. Then go to the <a href="/vlc/download.html">download
page</a>.

|15 apr 2002| Mirror Site | You probably experienced problems
recently to access the VideoLAN Web, FTP and CVS servers. This
was due to failure of the ISP. We have set up a mirror site with
Web; FTP and read-only CVS. When the ISP of the main site is
down, you will be automatically redirected to the mirror site.

|6 apr 2002| VideoLAN Quickstart | The <a
href="/doc/videolan-quickstart/videolan-quickstart.html">VideoLAN
Quickstart</a> describes how to start using VideoLAN quickly.
Basic skills on Linux and Network should be enough to understand
this Quickstart. It has been written by Bill Eldridge &lt;<a
href="mailto:bill@rfa.org">bill@rfa.org</a>&gt; and Alexis de Lattre
&lt;<a href="mailto:alexis@videolan.org">alexis@videolan.org</a>&gt;.

|6 apr 2002| Release: vlc 0.3.0 | This release fixes an amazing number
of bugs and brings a lot of new features as well: Configuration
file support, new input layer with IPv6 support and file format
autodetection, new video output engine featuring speed increases
up to 40%, VCD support under Mac OS X, multicast support and a
new interface for Win32, network support under BeOS, satellite
driver for WinTV Nova cards, video filters (deinterlacing,
rotation, distort, image wall) and much more! Read the <a
href="/vlc/changelog.html">ChangeLog</a> and go to the <a
href="/vlc/download.html">vlc download page</a>.

|6 apr 2002| Release: libdvdcss 1.1.1 | This bugfix release fixes
compilation issues under OpenBSD, IRIX and BeOS. You do not need to
upgrade if 1.1.0 worked properly for you. Otherwise, check the <a
href="/libdvdcss/index.html">libdvdcss</a> page!

|4 apr 2002| Release: vls 0.3.2 | Major update, a lot of new features
since 0.3.1: WinTV-Nova satellite receiver support, IPv6 support,
multicast improvement, user documentation and lots of bugfixes.
See <a href="/vls/changelog.html">changelog</a> and <a
href="/vls/download.html">download</a> pages.

|4 apr 2002| Release: libdvdcss 1.1.0 | This new release of the
most portable DVD descrambler is a lot more robust, includes a
new descrambling method, is now in sync with the Ogle group's own
version, features an HP-UX port, and fixes many bugs. Check the <a
href="/libdvdcss/index.html">libdvdcss</a> page for more information.

|3 apr 2002| Release: libdvbpsi 0.1.0 | This is the first official
release of libdvbpsi. It features PAT and PMT decoding and generation.
It is used by vls under Linux but the code is fully portable. Check the
<a href="/libdvbpsi/index.html">libdvbpsi</a> page for more information.

|25 mar 2002| Release: miniVLCS 0.1.2 | Small update, configuration file is now
a lot more simple to write but it can only support the newest vlc network syntax
(udp://). See the <a href="/network">network page</a> for more information and
download.

|5 mar 2002| Meuuh got his Ti!

|jan 2002| Linux Challenge: VideoLAN wins | Videolan is one of
the 25 winners of the IBM Linux Challenge for opensource projects
developed by university students. More information on the <a
href="http://www-1.ibm.com/linux/news/ilsc.shtml"> IBM Linux
Challenge</a> website.

|31 dec 2001| Release: vlc 0.2.92 | This release fixes an amazing number
of bugs, provides a new optimized buffer manager, fast memcpy routines,
MacOS X network input, BeOS CPU detection, DVD raw device support, a new
libmad audio decoder, and a new aRts audio output. Read the <a
href="/vlc/changelog.html">ChangeLog</a>
or go to the <a href="/vlc/download.html">download</a> page.

|6 dec 2001| Release: vls 0.3.1 | Major update, a lot of new features
since 0.3.0: Kfir video encoder support, plugins, file output, bugfixes.
See <a href="/vls/changelog.html">changelog</a> and <a
 href="/vls/download.html">download</a> pages.

|13 nov 2001| Release: vlc 0.2.91 | A bug-fix update,
with numerous fixes in the Win32 and MacOS X port,
and VCD support for Linux and BSD/OS.
See <a href="/vlc/changelog.html">changelog</a> and <a
href="/vlc/download.html">download</a> pages.

|13 nov 2001| Release: libdvdcss 1.0.0 | MacOS X, NetBSD and OpenBSD
ports were added to this version, along with new methods for descrambling
DVDs.

|10 oct 2001| Release: vlc 0.2.90 | Another major update,
with a new improved video decoder, a working Mac OS X
port with Altivec optimized routines, HTTP input support.
See <a href="/vlc/changelog.html">changelog</a> and <a
href="/vlc/download.html">download</a> pages.

|9 oct 2001| Release: vls 0.3.0 | This is the first official release
of the VideoLAN Server. It features MPEG1 PS, MPEG2 PS/TS, and DVD
streaming, a telnet interface, and runs under Linux and Solaris. Check
the <a href="/vls/index.html">vls</a> page for more information.

|24 aug 2001| Release: vlms 0.2.0 | The first version for more than
one year. Lots of bugfixes, and support for MPEG1 streams. See the <a
href="/vlms/index.html">vlms</a> page for more information.

|22 aug 2001| Release: libdvdcss 0.0.3 | Solaris port and BSD/OS ports
were added to this version.

|22 aug 2001| Release: vlc 0.2.83 | Minor release, with overlay subtitle
support.

|7 aug 2001| Release: vlc 0.2.82 | This version fixes lots of
issues discovered in 0.2.81, but also introduces the BSD/OS
port, and a few other Win32 improvements. See the usual <a
href="/vlc/changelog.html">changelog file</a> for a more
complete report on what has changed, or directly go to the <a
href="/vlc/download.html">download page</a>!

|2 aug 2001| Connection failure | We apologize for the 24 hour downtime
due to a power audit.

|28 jul 2001| Release: vlc 0.2.81 | This version comes after a huge
bug hunt, almost all critical bugs have disappeared, and all important
ones are gone. See the <a href="/vlc/changelog.html">changelog file</a>
for more information. This is also the first public version to use
libdvdcss. <a href="/vlc/download.html">Download</a> it now!

|28 jul 2001| Release: libdvdcss 0.0.2 | This new version brings lots
of bugfixes, full Windows 98 and Windows 2000 support, and a faster DVD
key handling. Get it on the <a href="/libdvdcss/">libdvdcss</a> page.

|26 jun 2001| Server failure | We apologize for the 24 hour server
downtime, but our server's motherboard fried and we experienced
additional RAID array issues. Recovery was, erm, fun.

|19 jun 2001| Release: libdvdcss 0.0.1 | <a
href="/libdvdcss/">libdvdcss</a> is the cross-platform library used
by vlc, the VideoLAN Client, to access DVDs with transparent CSS
decryption. It is the first library based on the vlc codebase, but
others are planned.

|5 jun 2001| Release: vlc 0.2.80 | A major step to 0.3.0,
with a somewhat working <a href="/vlc/windows.html">Windows
port</a>, network support which was gone since 0.2.0, additional
MMX and 3D Now! acceleration routines, still improved DVD
support, and the usual insane amount of bug fixes. Check out
the <a href="/vlc/download.html">download</a> page, and the <a
href="/vlc/changelog.html">changelog file</a>.

|16 may 2001| VideoLAN Client API documentation | <a
href="http://www.idealx.com/">IdealX</a>, a French Open Source
company, has had former VideoLAN team member Christophe Massiot
work full time on the vlc API documentation. It is available <a
href="http://www.idealx.org/en/doc/videolan-manual/">on the IdealX Open
Source web site</a>.

|1 may 2001| Release: VLAN server 0.0.1 | The VLAN server is now
released. Go to the <a href="/vlcs/download.html">download</a> page for
more information.

|28 apr 2001| Release: vlc 0.2.73 | Release just before we
break everything before freeze :-). Some bugfixes too (QNX and
FreeBSD) and enhancements to the xvideo module. Check out the
<a href="/vlc/download.html">download</a> page, and the <a
href="/vlc/changelog.html">changelog file</a>.

|16 apr 2001| Release: vlc 0.2.72 | A quick bugfix release which
solves issues introduced in 0.2.71 (crash at startup on BeOS and
MacOS X, and a few DVDs not working). Get your copy on the <a
href="/vlc/download.html">download</a> page.

|14 apr 2001| Port-specific pages created | We did a port-specific
page for each vlc port known to work, so that you can keep
track of what is happening to your platform's port. Currently
available port pages are <a href="/vlc/beos.html">BeOS</a>, <a
href="/vlc/linux.html">Linux</a>, <a href="/vlc/macosx.html">MacOS X</a>
and <a href="/vlc/solaris.html">Solaris</a>.

|13 apr 2001| Release: vlc 0.2.71 | This is a bugfix release which fixes
most of the issues discovered in 0.2.70: no more segfaults when compiled
with gcc 3.0pre and versions of gcc shipped with the latest RedHat
distributions, fixed the BeOS CSS decryption, fixed a few issues in IFO
parsing, fixed XVideo video output, and updated icons under Linux, BeOS
and MacOS X.

|9 apr 2001| Release: vlc 0.2.70 | After a long wait, version
0.2.70 of the VideoLAN Client is out. Amongst the news, the usual
bunch of bugfixes, even better DVD support under Gnome, Gtk+ and
BeOS, with on-the-fly chapter selection, language selection, a
playlist, an early MacOS X port, XVideo support, network input. <a
href="/vlc/download.html">Download it</a>.

|5 mar 2001| Release: vlc 0.2.63 | Bugfixes, bugfixes, and bugfixes
again, a Gtk+ interface for the Gnome-impaired, an even better
DVD support, and an interface and overlay support for BeOS. <a
href="/vlc/download.html">Get it</a> now.

|1 mar 2001| CVS snapshots available | There are so many
CVS commits that we could do a daily release, so a <a
href="/pub/videolan/vlc/snapshots/">daily VLC CVS snapshot</a> has just
been set up for people who can't wait.

|21 feb 2001| Release: vlc 0.2.62, with BeOS CSS support | Lots of
bugfixes, automatic hardware acceleration with SDL, enhanced DVD
title support, return of the framebuffer, Glide and GGI plugins,
various optimizations to the AC3 decoder, and, of course, the return
of the <b>BeOS port</b> with new features like drag'n'drop and <b>CSS
decryption</b>. Go and <a href="/vlc/download.html">get it</a> while
it's still hot!

|19 feb 2001| CVSWeb interface | We now have a <a
href="/cgi-bin/cvsweb/">CVSWeb interface</a> on the site.

|16 feb 2001| Release: vlc 0.2.61 | This new bugfix version brings
plain X11 support (which was broken), enhanced CSS support, a few new
interface features including drag'n'drop support, and fixes a few
reported bugs. As usual, <a href="/vlc/download.html">download</a> it
quickly!

|15 feb 2001| Hurricane vandalizes CVS repository | Bozo
"weeeeuuuuaaaaaaaaahhhhhhhhh, toupétéééééééé" Hurricane launched today
his vls code cleaning, which means he broke everything, but also that
vls is almost ready for a release.

|14 feb 2001| Release: vlc 0.2.60 | This new unstable version brings
astounding features over the stable one, like MPEG1 support, direct DVD
support, DVD decryption, arbitrary seeking in the stream, pause, fast
forward and slow motion, hardware YUV acceleration. Get it from the <a
href="/vlc/download.html">download</a> section!

|14 feb 2001| New website | The website has been simplified a lot,
because the old one was reported as confusing. Here it is, in all its
valid XHTML glory.

|2 feb 2001| First official release! | Director of École Centrale Paris
has <a href="/images/paper.jpeg">signed</a> the authorization to release
all the VideoLAN components under the GPL.

|31 jan 2001| See the new vlc at the Linux Expo in Paris | vlc has been
forked into two branches: stable (0.2.0, codenamed Onatopp) and unstable
(0.2.50, codenamed Urumov). Unstable has a lot of new interesting
features.

|20 jan 2001| Changed web server | We have moved the web site to our
brand new IBM server. Please let us know if anything goes wrong on the
web pages.

|07 dec 2000| VideoLAN on a floppy | For our beta-tests campaign on our
local network, we have created a boot floppy allowing non-Linux users to
boot off the floppy and load the vlc through an NFS mountage. It rocks!

|06 dec 2000| New beta-test campaign! | VideoLAN is not vlc. It's a
whole network solution; we are testing again, on our LAN, as many
improvements have been done to the three part of the project ( videolan
server, vlan solution, client ) since we last tested it. We expect about
50 to 100 beta-testers. See the test section if you are a student in the
Residence of the Ecole Centrale.

|22 nov 2000| For rh7.0 users ... | Redhat 7.0 users may have
difficulties to build the vlc, as the version included in rh7.0 isn't a
stable one. We advice you either to take the rpm or to downgrade to gcc
2.95

|27 aug 2000| Release: vlc 0.1.99i | A new version of the VideoLAN
client fixes a few display bugs, we now have field images support
and the motion compensation isn't buggy any more. Check the <a
href="/vlc/download.html">download</a> section.

|23 aug 2000| Release: vlms 0.1.99h | The VideoLAN mini server has been
released! Check the <a href="/vls/download.html">download</a> section.

|22 aug 2000| Release: vlc 0.1.99h | Check the <a
href="/vlc/download.html">download</a> section, as well as the <a
href="/vlc/changelog.html">changelog file</a>.

|16 aug 2000| Release: vlc 0.1.99g | Check the <a
href="/vlc/download.html">download</a> section, as well as the <a
href="/vlc/changelog.html">changelog file</a>.

|16 aug 2000| The moron of the week: Sam | Sam wrote a buggy Makefile
which prevented code to be compiled with optimizations. Now that this
issue has been fixed, we got a 40% speed increase!

|11 aug 2000| New TODO list | We did a <a href="/vlc/todo.html">TODO
list</a> for the 0.2.0 release. People wanting to help might pick up
ideas from this list.

|8 aug 2000| Release: vlc 0.1.99f | Check the <a
href="/vlc/download.html">download</a> section, as well as the <a
href="/vlc/changelog.html">changelog file</a>.

|20 jul 2000| Release: vlc 0.1.99e | This mostly fixes an urgent fix for
BeOS, see the <a href="/vlc/download.html">download</a> section.

|12 jul 2000| Release: vlc 0.1.99d | We are the 12th and vlc 0.1.99d
was just released. Check the <a href="/vlc/download.html">download</a>
section!

|15 jun 2000| Beta tests pre-release! | The client is being pre-released
today! Though the full network solution is not available yet, it already
lets you watch your favorite DVD with Linux!

|1 jun 2000| Screenshots online | Some <a
href="/screenshots/">screenshots</a> have been put online so that people
know VideoLAN isn't vaporware :)

|29 may 2000| More beta-tests | A beta-test campaign will take place on
the VIA network this week.

|23 mar 2000| New web site announcing release | We're getting closer to
a release, and we are preparing the web site for featuring dowloads and
bug fixes.

|27 feb 2000| Added a list of unencrypted DVDs | Most DVDs are
encrypted, but some are not. To encourage this, we provide a <a
href="/freedvd.html">list</a> of known unencrypted DVDs. Any body can
tell us 'Hey, this cool DVD is unencrypted'!

|4 feb 2000| VideoLAN thanks all visitors at the Linux Expo | We would  
like to thank all the visitors who showed interest in our project at    
the Linux Expo in Paris. Pictures of our stand will soon be available.  

|28 jan 2000| VideoLAN is going OpenSource! | We got almost all the
authorizations in order to distribute the VideoLAN components under the
General Public License. Our school director still needs to sign one
paper.

|24 jan 2000| More performance increase | Our new custom video decoder
gives us a 50% speed increase. We now can play DVDs at full framerate on
a Celeron 366 using framebuffer output, which makes the vlc the fastest
available software DVD player under Linux.<br /> According to Meuuh,
there're still many improvements that can be done.

|21 jan 2000| Presentation day photos available | Some photos of
the presentation day are available on VIA's website:<br /> <a
href="http://www.via.ecp.fr/assoce/videolan-20000121/">http://www.via.ec
p.fr/assoce/videolan-20000121/</a>

|05 jan 2000| VideoLAN will be at the Linux Expo
in Paris | Come to see VIA and the VideoLAN team
at the <a href="http://www.linux-expo.com/">Linux
Expo</a> in Paris. A map can be found here: <a
href="http://www.via.ecp.fr/assoce/linuxexpo.jpeg">http://www.via.ecp.fr
/assoce/linuxexpo.jpeg</a>.

|18 dec 1999| DVD, BeOS and framebuffer support") | The videolan client
now suports the Linux framebuffer output, and has been ported to
BeOS.<br /> Moreover, the mini-server now can emit a TS stream directly
from a DVD drive.

|10 dec 1999| Presentation day | A presentation day will take place
on <b>January the 21st, 2000</b>. Everyone interested in the project
is welcome to come and see it working. <br /><b>Find out more <a
href="presentation/">here</a>!</b>

|08 dec 1999| Beta-test has begun! | A large scale beta-test period has
just begun. Several members of the VideoLAN team have started testing
the VLAN solution now that the vlanbridge works. All students of the
Ecole Centrale are welcome to test the client with us, providing <b>they
have Linux and don't mind losing the Windows network neighbourhood for
the entire duration of the beta test</b>.

|16 nov 1999| Presentation day | A presentation day will take place in
january 2000 at the Ecole Centrale, in Paris. We expect to show you our
full MPEG2 solution. Find out more when the date has been chosen.

|15 nov 1999| New website | The website has been updated. It had been
about one year since nothing had changed here (we were too busy coding
*g*). Expect to find here as much as we are allowed to give away in a
few weeks, starting from screenshots or hopefully more.

|22 oct 1999| Huge performance increase on the vlc | Thanks to Polux,
who rewrote the YUV transformation in the vlc using MMX assembly, a mere
P2-300 can now display about 12fps of MPEG2 video.

|empty entry to prevent script from mangling the last entry
