# Subdirectories to be preprocessed
SUBDIR = doc events removed rez streaming support team vlc stats

# Files to be preprocessed
#PHP_FILES = # automatic
PHP_IGNORES = mirror retrieve

# Additionnal dependencies

news.html: news.msg

index.html: news.msg

