# Subdirectories to be preprocessed
SUBDIR = doc events removed rez streaming support team vlc

# Files to be preprocessed
#PHP_FILES = # automatic
PHP_IGNORES = mirror

# Additionnal dependencies

news.html: news.msg

index.html: news.msg

