# Comments begin with a #
# New topics begin with a "|"
#
|9 January 2011|VLC for iOS removed from the AppStore|The VideoLAN project has been notified that the build of VLC for iOS that was submitted on the AppStore by the company Applidium has been removed by Apple from the iOS AppStore.<br />The VideoLAN non-profit organisation is a 3rd party in this matter and, while VideoLAN regrets the annoyance that could be caused to the users, VideoLAN is not responsible for this matter.<br />However, we are going to work and try to discuss with all the parties to find the best solution in the shortest time possible.

|16 December 2010|VLC users survey|The VideoLAN project and the VLC development team would love <b>VLC users</b> and <b>community</b> to help them in understanding the users and their needs.<br />Please <b>fill</b> the <a href="http://goo.gl/oTISI">VLC users survey</a>. It is quick and is completely anonymous.

|22 November 2010|Google Code-In starts!|VideoLAN is one of the organization selected by <a href="http://code.google.com">Google</a> for the <a href="http://code.google.com/opensource/gci/2010-11/index.html">Google Code-In program</a>.<br /> If you are a student, between 13 and 18 years old, you can apply to help the VideoLAN project. <b>Tasks</b> include code and <b>not-code</b> short amount of work that will help greatly the VideoLAN project.<br /><a href="http://code.google.com/opensource/gci/2010-11/index.html">Join Now!</a>

|13 November 2010|VLC 1.1.5|VideoLAN and the VLC development team are proud to present VLC 1.1.5, the fifth bugfix release of the VLC 1.1.x branch.<br />Small new features, notably GME and live .webm support and an integrated listing of web-shows directly in the playlist are making this release. Many bugfixes, updated translations and <a href="/security/sa1006.html">security issue</a> are also part of this release.<br />Source and Windows and MacOSX builds are available.<br />See the <a href="/vlc/releases/1.1.5.html">release notes</a> for more information.

|27 September 2010|VLC 1.1.4.1|VideoLAN and the VLC development team are happy to present VLC 1.1.4.1, a fourth bugfix release of the VLC 1.1.x branch.
This release does only target PowerPC-based Macs. It is the first release of this branch for this platform and includes all the features, improvements and bug-fixes you have been waiting for.<br />This is a <b>security update</b>, so we recommend all users to update to this new version (CVE-2010-2937 / <a href="http://www.videolan.org/security/sa1004.html">VideoLAN-SA-1004</a>).

|27 August 2010|VLC 1.1.4|VideoLAN and the VLC development team are proud to present VLC 1.1.4, the fourth bugfix release of the VLC 1.1.x branch.<br />An important class of security issues was discovered on Windows, and VLC and many other important applications on Windows are affected; see our <a href="/security/sa1005.html">security advisory</a>.<br />Source and Windows builds are available.<br />See the <a href="/vlc/releases/1.1.4.html">release notes</a> for more information.

|18 August 2010|VLC 1.1.3|VideoLAN and the VLC development team are proud to present VLC 1.1.3, the third bugfix release of the VLC 1.1.x branch.<br />Some more bugs were squashed and a <a href="/security/sa1004.html">potential security issue</a> leading to a crash, was discovered. On top of that, this release introduces small fixes and improvements over VLC 1.1.2, for most platforms.<br />Source code and binaries for Windows and Mac (Intel) are available.<br />See the <a href="/vlc/releases/1.1.3.html">release notes</a> for more information.<br /><b>NB:</b> first Windows installer were corrupted, please use the updated ones.

|10 August 2010|New project: libaacs|A new project is now hosted by VideoLAN: <a href="/developers/libaacs.html">libaacs</a>.<br /> Mostly made by developers from <a href="http://www.doom9.org">Doom9</a>, this <b>research</b> project implement the public <a href="http://www.aacsla.com/specifications/">AACS specification</a>.<br /> <b>NB:</b> libaacs is a research project and does not distribute any key.

|29 July 2010|VLC 1.1.2|VideoLAN and the VLC development team are proud to present VLC 1.1.2, the second bugfix release of the VLC 1.1.x branch.<br />After just ten days of 1.1.1, some more bugs were squashed, hence a new release. This release introduces small fixes and improvements over VLC 1.1.1, notably on Windows.<br />Source code and binaries for Windows and Mac (Intel) are available.<br />See the <a href="/vlc/releases/1.1.2.html">release notes</a> for more information.

|24 July 2010|VLC 1.1.1 for Mac|This is just a short update to inform our users that VLC 1.1.1 binaries for Mac Intel have arrived. They should fix the Multi-Channel crashes of the 1.1.0.<br />See <a href="/vlc/releases/1.1.1.html">release notes</a> for more information.

|21 July 2010|VLC 1.1.1|VideoLAN and the VLC development team are proud to present VLC 1.1.1, the first bugfix release of the VLC 1.1.x branch.<br />After almost one month and more than 17 million downloads of the VLC 1.1.0, this release introduces numerous fixes and small improvements over VLC 1.1.0.<br />Source code and binaries for Windows are available, other operating systems will come later.<br />See the <a href="/vlc/releases/1.1.1.html">release notes</a> for more information.

|17 July 2010|New project: libbluray|A new project is now hosted by VideoLAN: <a href="/developers/libbluray.html">libbluray</a>.<br /> Mostly made by developers from <a href="http://www.doom9.org">Doom9</a>, this library aims at integration of Blu-Ray movies playback into media players, like <a href="/vlc/">VLC</a> and VLC's competitors.<br /> <b>NB:</b> This library <b>does not</b> break any DRM.

|02 July 2010|VLC 1.1.0 and GPU decoding on ATI|The latest released version of VLC, 1.1.0, that was out a week ago, and has been downloaded half-a-dozen millions times so far, has added GPU acceleration for HD decoding under Linux and Windows. On Windows, as already stated, the code isn't working correctly with AMD Radeon cards.<br />Therefore, we have been working with AMD on this topic and after common work, we are going to release a new version of VLC, versionned as 1.1.1, that will work with the upcoming ATI Catalyst 10.7 driver. AMD did provide us a beta of this driver and we have verified successfully that GPU acceleration works.<br /> Thanks for your understanding and your support.

|22 June 2010|VLC 1.1.0|VideoLAN and the VLC development team are proud to present the first major release of the 'The Luggage' branch of the popular media player and media framework.<br />This release brings many major improvements, especially: GPU and DSP decoding on selected platforms, new support for codecs, demuxers and muxers, Lua extensions and Lua content extensions (luaSD), improved interfaces, Video Output rework, removal of lots of modules, rewrite of many in order to improve performance, in CPU, RAM and I/O. It introduces also new libVLC and new bindings and improves the port on many platforms.<br /><a href="/vlc/releases/1.1.0.html">Learn more about the release</a>.

|21 June 2010|VLC 1.1.0 removes SHOUTcast support|VideoLAN is sad to announce that, starting from VLC 1.1.0, the SHOUTcast module is not available on the distributed VLC any longer, because AOL Corporation is hindering Open Source Software.<br />AOL wants to force VLC to be relicensed to <b>close-source</b> and shipped with an <b>adware</b> software from them.<br />You can find <a href="/press/2010-1.html">more information</a>.

|27 May 2010|VLC 1.1.0 Release Candidate 1|VideoLAN and the VLC developers are proud to announce the first Release Candidate of the <b>1.1.0</b> version of VLC.<br />This test release, aimed at power-users is a major update on the current VLC 1.0.x branch. It includes numerous changes, modification and improvements, including GPU/DSP decoding, support for more formats and codecs and extensions.</p><p>Source and full Changelog are <a href="/vlc/releases/1.1.0-RC.html">available now.</a>

|25 Apr 2010|x264 achieves Blu-Ray Compatibility|The <a href="/developers/x264.html"><b>x264</b> project</a> has announced the first free software encoder to be able to generate Blu-ray compliant video. In addition, the announcement comes with a <a href="http://x264.nl/x264_Demo_Blu-ray.torrent">torrent</a> of an x264-encoded Blu-ray disc containing entirely free content, such as the Open Movie Project videos.<br /> While there are still no free software Blu-ray authoring tools, hopefully this will change now that video and audio are taken care of so that everyone will be able to make their own Blu-rays without expensive proprietary software. <b>Grab your <a href="http://x264.nl/x264_Demo_Blu-ray.torrent">torrent</a> now!</b>. <a href="http://x264dev.multimedia.cx/?p=328">Know more about this achievement!</a>

|21 Apr 2010|VLC 1.0.6|The VLC development team is proud to introduce a new version of its 'Goldeneye' branch. This release bridges the gap between version 1.0.5 and the upcoming 1.1.0 VLC release. It fixes <a href="/security/sa1003.html">several vulnerabilities</a> which were uncovered during the development of VLC 1.1.0. It also introduces a number of additional stability and other fixes.

|06 Apr 2010|Google Summer of Code student applications|Students that want to work for <a href="/">VideoLAN</a> during the summer, with the <a href="http://code.google.com/soc/">Google Summer of Code</a> program should remember to send applications before Friday, April 9th 2010, 19:00 UTC, on the <a href="http://socghop.appspot.com/">webapplication</a>. <br />You shouldn't wait for the last minute and we would like to remember that application can be modified afterwards and that you can submit multiple applications.

|01 Apr 2010|April Fools: VideoLAN acquired by RealNetworks|<b>April Fools' !</b><br />VideoLAN is proud to announce that it has been acquired by <a href="http://www.real.com">RealNetworks</a>, the world's premiere provider of Internet media delivery tools.  RealNetworks will be working with VideoLAN over the next few months to leverage the powerful Real toolset to improve VLC media player and other VideoLAN software.</p> <p>Accordingly, with the introduction of Real's superior solutions, we will be dropping all other encoders from the streaming component of VLC media player.  Additionally, to better serve our customers, we will be introducing a new VLC media player Pro application, with cutting edge streaming capabilities and the ability to play back and edit all Real video and audio formats.  This new application will be available for the low low price of $30/€30.  We hope you enjoy the new VLC media player! <br />
<b>April Fools' !</b>


|22 Mar 2010|Outdated security issue|So-called "Security" teams are spreading wrong information about an "unpatched" security issue in VLC.<br /><a href="http://xforce.iss.net/xforce/xfdb/55717">ISS</a> and <a href="http://www.securityfocus.com/bid/37832">SecurityFocus</a> are presenting a security issue in versions of VLC, that are, in fact, more than 2 years old. This issue has been <a href="/security/">fixed</a> since a long time and since <strong>20 versions</strong> of VLC.</p><p>Of course, the latest version of VLC <strong>isn't affected</strong>.


|01 Mar 2010|Multicat 1.0|Multicat is a set of tools designed to easily and
efficiently manipulate multicast streams in general, and MPEG-2
Transport Streams in particular.<br />
VideoLAN is glad to announce the first public release of this new software, released under the <a href="http://www.gnu.org/licenses/old-licenses/gpl-2.0.html">GPL license</a>.
Visit the <a href="http://www.videolan.org/projects/multicat.html">project page</a> or proceed to download <a href="http://downloads.videolan.org/pub/videolan/multicat/1.0/multicat-1.0.tar.bz2">Multicat</a>.

|01 Mar 2010|DVBlast 1.2|The DVBlast team is happy to announce version 1.2 of DVBlast. DVBlast is a powerful and simple streaming application for DVB cards under Linux. In addition to numerous fixes, this new release also brings new features such as DVB-ASI or UDP/RTP inputs, and IPv6 support.<br />
Visit the <a href="http://www.videolan.org/projects/dvblast.html">project page</a> or proceed to download <a href="http://downloads.videolan.org/pub/videolan/dvblast/1.2/dvblast-1.2.tar.bz2">DVBlast</a>. Please note that it requires <a href="http://www.videolan.org/developers/libdvbpsi.html">libdvbpsi</a>.

|28 Feb 2010|VideoLAN security advisory 1001|<a href="http://www.videolan.org/security/sa1001.html">A bug in Clam AntiVirus</a> hinders use of VLC media player 1.0.5 for Windows.

|6 Feb 2010|VideoLAN at FOSDEM|The VideoLAN team will be at <a href="http://www.fosdem.org/2010">FOSDEM</a> in Brussels. If you have some time we will be happy to welcome you on our booth. We will do some demonstration about some nice features on the road for the next major release like extensions.

|31 January 2010|VLC 1.0.5|VideoLAN and the VLC developers are very proud to announce their latest release of VLC. After more than 51 million downloads of VLC 1.0.3, this version is specially aimed towards Windows and Mac platforms, and <a href="http://www.videolan.org/developers/vlc-branch/NEWS">brings various fixes, speed improvements and translations updates.</a><br /> The Windows version benefits speed-ups from both an updated compiler (gcc 4.4.2) and codecs updates.<br />The Mac version brings support for the latest Apple Remote and updated codecs too.</p><p><strong>Some antivirus have wrongly detected a virus in the Windows release</strong>, if you want the VideoLAN team can suggest better antivirus or operating sytem, on request.</p><p>Be careful, VLC 1.1 is on the road!


|21 December 2009|End of VideoLAN Dev Days '09|The second edition of the VideoLAN Dev Days is now finished and was a great success.<br />New project were presented, ideas about the future of VideoLAN and VLC were shared and technical issues could be discussed.</p><p>We would like to thank a lot everybody who participated to the event and, of course, our great sponsors without this event could not happen : <a href="http://www.epitech.eu/">Epitech</a>, <a href="http://www.iledefrance.fr/">région Île de France</a> and <a href="http://www.anevia.com/">Anevia</a>.

|17 December 2009|VideoLAN Dev Days '09 J-1|The VideoLAN organisation, the VLC, VLMa and DVBlast developers are inviting <strong>you</strong> to come and meet us, in Paris, France, from Friday 18th to Sunday 20th December 2009.<br />Open Party will happen on Friday night at <a href="http://lacantine.org/events/videolan-party">La Cantine</a>.<br />Other events will happen during 3 days: <a href="/videolan/events/vdd09.html">program and details</a>. Free registration is mandatory!</p><p>We would like to thanks our sponsors: <a href="http://epitech.eu/">Epitech</a> and <a href="http://www.anevia.com/">Anevia</a>.

|11 December 2009|VideoLAN party next friday!|The VideoLAN organisation, the VLC, VLMa and DVBlast developers are inviting you to come and meet us, in Paris, France, on Friday 18th December 2009.<br /> Presentations about VideoLAN, next version of VLC and other cool projects will be held. This is a unique occasion to meet all the VLC developers!</p><p>Registration is <strong>MANDATORY</strong>. Details can be found on: <a href="http://lacantine.org/events/videolan-party">La Cantine's Website</a> and on our <a href="http://twitter.com/videolan">twitter</a> account.

|10 December 2009|VLC 1.0.4|The VLC development team is quite happy to introduce a new version of its 'Goldeneye' branch. This release is targetted at fixing bugs on the X11 platforms, fixing bugs especially for KDE, cairo-dock, XCB, v4l and FreeBSD compatibility. Binaries for Windows and Mac OS are not yet on the pipe.

|1 December 2009|VideoLAN Dev Days '09|The <a href="/videolan/">VideoLAN non-profit organisation</a> is happy to invite you to the multimedia open-source event of this end of year: <br /><strong>VideoLAN Dev Days '09</strong>.</p>
<p>For the second time, people from the VideoLAN community will meet in <strong>Paris</strong> to gather, work, discuss and build a stronger community, on the <strong>18th, 19th and 20th of december 2009</strong>.</p><p><a href="/videolan/events/vdd09.html">Details and program</a> are available.

|23 November 2009|DVBlast 1.1|The DVBlast team is happy to announce version 1.1 of DVBlast. DVBlast is a powerful and simple streaming application for DVB cards under Linux. In addition to numerous tuning and descrambling fixes, this new release also brings new features such as EIT pass-through (for EPG) or DVB Diseqc.<br />
Visit the <a href="http://www.videolan.org/projects/dvblast.html">project page</a> or proceed to download <a href="http://downloads.videolan.org/pub/videolan/dvblast/1.1/dvblast-1.1.tar.bz2">DVBlast</a>. Please note that it requires <a href="http://www.videolan.org/developers/libdvbpsi.html">libdvbpsi</a>.

|10 November 2009|VLC 1.0.3 and Mac OS X 10.6.2|The VLC developers are glad to report that Apple's recently announced Mac OS X update to version 10.6.2 includes a fix which let's correctly you use the Apple Remote within VLC again. Prior releases of Apple's Mac OS X 10.6 included a bug, which caused interferences with iTunes or DVD Player when using the Apple Remote in 3rd party applications. According to Apple, this update also addresses video playback and performance issues on certain setups.<br />
Please note that VLC 1.0.3 is required to use the Apple Remote on Mac OS X 10.6.2. 

|31 October 2009|VLC 1.0.3 Release|The VLC developers are glad to bring you a new version of the award-winning VLC. This version <a href="http://www.videolan.org/developers/vlc-branch/NEWS">brings a various improvements and fixes</a>, and especially an important issue with Windows® 7 that worsened the video quality of the default output of VLC. VLC 1.0.3 has been tested to meet all of the technical requirements to be «Compatible with Windows® 7»<br />
 This release also provides new deinterlacer filters, fixes for the interface and the WMA Professional support on Windows. <br />
<b>Update:</b> Binaries for Mac OS X are now available.

|22 October 2009|VLC 1.0.3 Release Candidate and Windows 7| The VLC developers are very glad to offer you the first release candidate of the third minor update of the popular "Goldeneye" version of VLC.<br />
This version <a href="http://www.videolan.org/developers/vlc-branch/NEWS">brings a few improvements and fixes</a>, and especially fixes an important issue with Windows® 7 that worsened the video quality of the default output of VLC. As Windows® 7 will be available today, the windows maintainers of VLC wanted to sync with this release.<br />
This release candidate provides also updated translations, new deinterlacer filters, fixes for the interface and the WMA Professional support on Windows. Please <a href="ftp://ftp.videolan.org/pub/testing/vlc-1.0.3-rc/">test</a> this release candidate and report bugs. <a href="ftp://ftp.videolan.org/pub/testing/vlc-1.0.3-rc/win32">Windows binaries</a> are available.<br />
<b>Update:</b> Binaries for Mac OS X are available <a href="ftp://ftp.videolan.org/pub/testing/vlc-1.0.3-rc/macosx">here</a>.

|10 October 2009|VLC is Compatible with Windows® 7|<img alt="Compatible with Windows 7 Logo" src="http://images.videolan.org/images/partners/EN-w7-comp_rgb_S.png" style="float:left; margin: 15px;"/> The VLC developers are happy to announce that the latest version of VLC, 1.0.2, has been tested to meet all of the technical requirements to be Compatible with Windows® 7. This means that VLC is tested for compatibility and reliability on Windows® 7, has passed Microsoft designed tests to minimize the possibility of crashs, hangs, and reboot and installs cleanly and reliably. <br /> While this shows that you can have confidence in installing VLC on your Windows® 7 installation, there are still bugs on the visual quality, depending on your video driver. See <a href="http://wiki.videolan.org/VLC_Windows7">our wiki</a> for more details.

|01 October 2009|Meet people from the VideoLAN team on T-DOSE 2009 (3 and 4 October)|The dutch based conference <strong>T-DOSE</strong> is being held for the fourth year in a row and has interesting talks. If you want to meet people from VideoLAN project and know more about VLC 1.0 then meet us at the booth. People from VideoLAN team will be present at the T-Dose conference in the next days. For more information on T-DOSE schedule visit this <a href="http://www.t-dose.org/2009/schedule">link</a>.

|22 September 2009| VLC 1.0.2 is out!| After almost 2 months and 27 million downloads of VLC 1.0.1, the VLC team is proud to present the third version of the Goldeneye branch of VLC: <strong>1.0.2</strong>!</p><p>This version introduces many fixes, notably for SSA decoding, v4l2, MacOS interface, ogg/theora, x264 modules and <a href="/security/sa0901.html">security issues</a>. It also introduces the port to 64bits for Mac OS platform and 2 new languages (Kazakh and Croatian).<br /> Because of the security issues, we strongly recommand everybody to update its version of VLC.

|13 August 2009|VLC Skin Editor 0.8.5 is out!|The VideoLAN team is pleased to announce the release of a new version of the VLC Skin Editor.<br/>
This version brings again bugfixes and performance improvements but also new features. Among these is the ability to edit Slider curves with the
mouse and support for the generation of vertical slider backgrounds. Downloads are available on the <a href="http://www.videolan.org/vlc/skineditor.html">Skin Editor page</a>.

|28 July 2009|VLC 1.0.1 is out!|VideoLAN is pleased to announce the release of the second version of the Goldeneye branch of VLC: <strong>1.0.1</strong>!</p><p>3 weeks after the release of <strong>1.0.0</strong>, and with almost <strong>14 million</strong> downloads, this minor version fixes most of the notable bugs and regressions that were present in the 1.0.0 version.<br />Notable fixes and improvements include:</p>
<ul class="bullets">
<li>fix flv and mpeg2 seeking,</li>
<li>fixes for wmv, wav, rtsp and ssa support,</li>
<li>fixes for Qt and Mac OS X interface,</li>
<li>fix an integer underflow in Real pseudo-RTSP module,</li>
<li>updates of some translations,</li>
<li>port of the ZVBI module to Windows for full teletext support and</li>
<li>codecs updates for Windows and Mac OS X versions. </li>
</ul>
<p>This version is ready to <a href="http://www.videolan.org/vlc/">download</a>! Learn <a href="http://wiki.videolan.org/Changelog/1.0.1">more details about this release</a>!<br />Press and related questions should be forwarded to <a href="/contact.html">VideoLAN</a>.

|28 July 2009|VLC 0.9.10|VideoLAN is pleased to announce another bugfix release for the Grishenko branch of VLC.<br />This version mostly targets the Mac OS X 10.4 platform. It includes various improvements and bugfixes for this port as well as updates to access, stream out and decoder modules plus certain third party libraries. The integer underflow fix from VLC 1.0.1 is also included. More <a href="http://wiki.videolan.org/Changelog/0.9.10">details are available on the wiki</a>. <br />We recommend all Mac OS X 10.4 users to update to this release. <strong><a href="http://www.videolan.org/vlc/download-macosx.html">Download now</a>.</strong>

|10 July 2009|VLC 1.0.0 hits 3 million downloads|After less than 3 days, the 1.0.0 release of VLC has hit more than 3 million downloads on the <a href="/stats/downloads.html">download counter</a>. We would like to thank the people who have downloaded it and especially, people who have donated to our cause.

|07 July 2009|VLC 1.0.0|The VideoLAN project is pleased to announce the release of the first version of the Goldeneye branch of VLC: 1.0.0.</p><p>This major release introduces many new features, new formats and new codecs to the VLC multimedia framework and fixes a very high number of bugs that were present in the 0.9.x or 0.8.6 versions.<br />You can <a href="http://www.videolan.org/vlc/">download it now</a>.<br />The VLC project only lives with volunteers and would love help from new users and contributors: time, code, hardware and money would help us a lot. You don't need to be a developer to help.

|25 June 2009|VideoLAN at LinuxTAG|Once again, The VideoLAN Team got a booth at <a href="http://www.linuxtag.org">LinuxTAG</a> (June 24 to June 27) in Berlin, Germany. Come around and meet us in hall 7.2a at booth 105. Have a look at the latest and greatest features and see the people behind the cone.

|20 June 2009|VLC 1.0.0 approaches!|Thanks to the continuous efforts made by the developers and the community, the new version of the award-winning VLC media player, numbered 1.0.0, is approaching the end of development. <br />
The release will very likely happen next week.<br />
We would like to thank all the people involved with it.<br />
Our skin contest is now closed, thanks for participation.

|18 June 2009|Skins contest vote and VLC 1.0.0-rc4|The skins contest is now over, and we have 6 skins that fullfilled the requirements. You can <a href="http://www.videolan.org/vlc/contest/">vote now!</a>.<br />At the same time, the VideoLAN project is glad to announce that the fourth release candidate (and hopefully last!) of the <em>Goldeneye</em> version of VLC, numbered <em>1.0.0-rc4</em> is out.<br />
Source tarballs are ready, but binaries should follow very soon on <a href="http://download.videolan.org/pub/testing/vlc-1.0.0-rc4/">our main website</a>.

|8 June 2009|VLC 1.0.0-rc3 and skins contest|The VideoLAN project is glad to invite you to <span style="color: red;"><strong>test</strong></span> the third release candidate of the <em>Goldeneye</em> version of VLC, numbered <em>1.0.0-rc3</em>.<br /><a href="http://www.videolan.org/mirror-geo.php?file=testing/vlc-1.0.0-rc3/vlc-1.0.0-rc3.tar.bz2">Source tarballs</a>, <a href="http://www.videolan.org/mirror-geo.php?file=testing/vlc-1.0.0-rc3/win32/vlc-1.0.0-rc3-win32.exe"> Windows binaries </a> and <a href="http://ftp.videolan.org/pub/testing/vlc-1.0.0-rc3/macosx/"> Mac OS binaries </a>  are already available for download. Changes can be found <a href="/developers/vlc/NEWS">here</a>.<br />
VideoLAN would like to mention that the <a href="http://wiki.videolan.org/Skins2_Contest">Skins2 contest</a> is still going on. To develop a skin, you can use our new <a href="/vlc/skineditor.html">VLC Skin Editor</a>. Please share this contest news on your prefered social bookmarking or news site.

|28 May 2009|VLC 1.0.0-rc2 and skins contest|The VideoLAN project is glad to invite you to <span style="color: red;"><strong>test</strong></span> the second release candidate of the <em>Goldeneye</em> version of VLC, numbered <em>1.0.0-rc2</em>.<br /><a href="http://www.videolan.org/mirror-geo.php?file=testing/vlc-1.0.0-rc2/vlc-1.0.0-rc2.tar.bz2">Source tarballs</a>, <a href="http://www.videolan.org/mirror-geo.php?file=testing/vlc-1.0.0-rc2/win32/vlc-1.0.0-rc2-win32.exe"> Windows binaries </a> and <a href="http://ftp.videolan.org/pub/testing/vlc-1.0.0-rc2/macosx/"> Mac OS binaries </a>  are already available for download. Changes can be found <a href="/developers/vlc/NEWS">here</a>.<br />
VideoLAN would like to mention that the <a href="http://wiki.videolan.org/Skins2_Contest">Skins2 contest</a> is still going on. To develop a skin, you can use our new <a href="/vlc/skineditor.html">VLC Skin Editor</a>. Please share this contest news on your prefered social bookmarking or news site.

|13 May 2009|VLC 1.0.0-rc1 and skins contest|The VideoLAN project is glad to invite you to <span style="color: red;"><strong>test</strong></span> the first release candidate of the <em>Goldeneye</em> version of VLC, numbered <em>1.0.0-rc1</em>.<br /><a href="http://www.videolan.org/mirror-geo.php?file=testing/vlc-1.0.0-rc1/vlc-1.0.0-rc1.tar.bz2">Source tarballs</a> and <a href="http://www.videolan.org/mirror-geo.php?file=testing/vlc-1.0.0-rc1/win32/vlc-1.0.0-rc1-win32.exe"> Windows binaries </a> are already available for download. Changes can be found <a href="/developers/vlc/NEWS">here</a>.<br />
VideoLAN would like to take the opportunity to mention the <a href="http://wiki.videolan.org/Skins2_Contest">Skins2 contest</a> we are organizing during this release cycle time. To develop a skin, you can use our new <a href="/vlc/skineditor.html">VLC Skin Editor</a>. Please share this contest news on your prefered social bookmarking or news site.|<br />VLC 1.0.0-rc1, codename Goldeneye, is a <strong>test</strong> release of the <em>1.0.0</em> version of VLC. It introduces many new codecs, various playback core improvements (frame-by-frame, live-recording, instant pausing, etc...), interface improvements, new features and many bugfixes. We encourage people to test and report regressions that could have crept in this release.

|12 May 2009|DVBlast 1.0|<a href="/projects/dvblast.html">DVBlast</a> is a simple and powerful streaming application for linux-dvb devices. It opens a DVB device, tunes it, places PID filters, configures a CAM module, and demultiplexes the packets to several RTP outputs.<br />
The VideoLAN project is glad to announce the first public release of this new software, released under the <a href="http://www.gnu.org/licenses/old-licenses/gpl-2.0.html">GPL license</a>.

|05 April 2009|VLC media player 0.9.9a for Mac OS X|This update is Mac OS X only. It fixes VLC's behaviour on PowerPC-based Macs and includes updated libraries for all Mac OS X platforms.<br />
In order to take full advantage of VLC 0.9.9's features, including native Real Video playback, we recommend all Mac users to update to this new release.<br /> Due to a lack of active Mac OS X developers, these issues remained unnoticed for the last release. We are sorry for the noise and are looking for enthusiastic Mac developers to help and support us.

|02 April 2009|VLC media player 0.9.9|The VideoLAN team is very pleased to announce the release of <a href="/vlc/">VLC media player 0.9.9.</a><br /><br />
This is a <em>bugfix</em> release on the 0.9 branch of VLC. Notables bugfixes are:</p>
<ul class="bullets">
<li>fullscreen behaviour on <a href="/vlc/download-windows.html">Windows</a> with multiple screens,</li>
<li>workaround bug with libxml2 >=2.7.3,</li>
<li>video performance on Intel-based Macs,</li>
<li>various decoders updates on Windows.</li>
</ul>
<p>
An experimental native decoder for Real Video 3.0 &amp; 4.0 using FFmpeg has been added and many fixes happened in our Real Media demuxer.<br />This should improve Real Media Files support on all platforms.

|1 April 2009|A New Logo for a Brighter Future|<img alt="logo" src="http://images.videolan.org/images/news/bulldozer-small.gif" style="float:left;"/>After years of faithful service, we've decided to retire our old logo, the famous cone. It served its purpose, but as VLC 1.0.0 is approaching, we are dropping the passive cone and upgrading to some heavy machinery. <br />The whole team would like to welcome the new VLC logo: <a href="http://images.videolan.org/images/news/bulldozer.png">Bulldozer</a>! Get ready for some serious earth shattering on the open source multimedia world!<br/>VLC 1.0.0 is warming up... maybe it's not going to be fast but it will wreck everything in its path.</p><p class="clearme"><br/>
<span style="color:red;"><b>Note:</b> Look at the date...</span>

|25 March 2009|VideoLAN in Google Summer of Code|VideoLAN has been accepted as an official mentoring organisation for <a href="http://socghop.appspot.com/">Google's 2009 edition of Summer of Code</a>. We are looking for interested students that are free this summer. Students can apply now and suggest projects. See <a href="http://wiki.videolan.org/SoC_2009">VLC related projects</a> and <a href="http://wiki.videolan.org/SoC_x264_2009">x264 related projects</a>. Feel free to drop by on IRC or e-mail the vlc-devel@ mailing list if you have any questions.

|23 February 2009|VLC Skin Editor 0.8.1|The VideoLAN team is pleased to announce the release of VLC Skin Editor 0.8.1.<br />
It fixes several bugs and brings better performance. Furthermore the program is now available in several languages.<br />
All users are recommended to upgrade to this release. You can download it from <a href="http://www.videolan.org/vlc/skineditor.html">the Skin Editor page</a>.

|24 December 2008| End of VideoLAN Dev Days '08| The VideoLAN Dev Days '08, our first real life meeting were a great success. Many development and organisation ideas were discussed there. We want to thank everyone that came to see us and the four companies that sponsored us: <a href="http://www.anevia.com">Anevia</a>, <a href="http://free.fr">Free</a>, <a href="http://m2x.nl">M2X</a> and <a href="http://www.uniways.fr">Uniways</a>.<br />
Happy holidays and Merry Christmas to everyone.

|10 December 2008| VideoLAN Dev Days '08| The VideoLAN community is a fast-evolving and ever-changing community and development happens really fast.
While this is fun, it is always difficult to meet and discuss with each other in person.<br />
Therefore, we are happy to invite you to: <strong> The VideoLAN Dev Days '08 </strong>, in Paris, France, on the 20-21 December week-end.<br />
If you are a developper, a VLC fan or press, and you are interested to come or discuss with the team, please <a href="/videolan/">contact us</a>.<br />
We would like to thank the four companies that sponsor us: <a href="http://www.anevia.com">Anevia</a>, <a href="http://free.fr">Free</a>, <a href="http://m2x.nl">M2X</a> and <a href="http://www.uniways.fr">Uniways</a>.<br />
<b>Update:</b> You can have a look at the meeting <a href="http://www.videolan.org/events/">here</a>.

|08 December 2008| VLC 0.9.8a binaries for Windows and Mac OS|VLC media player 0.9.8a binaries for <a href="http://www.videolan.org/vlc/download-windows.html">Windows</a> and <a href="http://www.videolan.org/vlc/download-macosx.html">MacOS</a> are now available.<br />
We strongly recommend all users to update to this new version.
|03 December 2008| VideoLAN Security Advisory 0811 | VLC media player versions 0.9.8 and older suffer from a critical buffer overflow vulnerabilities.
<a href="http://www.videolan.org/security/sa0811.html">Refer to our advisory</a>
for technical details.
Fixes for this issue is available in VLC 0.9.8a.
We strongly recommend all users to update to this new version.<br />
Windows and Mac OS builds are coming at a later date.

|24 November 2008|VLC media player SourceForge Award|<img src="http://people.videolan.org/~jb/SourceForge_Award/thumbnails/012-VLC_SourceForge_Awards-013.jpg.small.jpeg" alt="Sourceforge VLC award" style="float:left; margin-right:5px"/>
VLC media player won <a href="http://sourceforge.net/community/cca08/" hreflang="en">a Community Choice Award</a>, organised by our friends from SourceForge, this summer. We just received the award.<br />
The whole VideoLAN Team would love to thank many times SourceForge and especially Ross Turk.<br />
You can find more infos <a href="http://people.videolan.org/~jb/SourceForge_Award/">here</a> and <a href="http://www.jbkempf.com/blog/post/2008/11/24/SourceForge-Award-Trophee-for-VLC">there</a>.<br />

|14 November 2008|A problem with Windows 0.9.6 binary|The released 0.9.6 Windows binary presents some issues in the avformat module that can prevent playback of FLV or MXF files. We apologize for this, and corrected the builds accordingly.<br />
You can download the correctly builds on <a href="http://www.videolan.org/mirror-geo.php?file=vlc/0.9.6/win32/vlc-0.9.6-win32.exe">your favorite mirror</a>.

|06 November 2008|VLC media player 0.9.6|The VideoLAN team is pleased to announce the release of VLC media player 0.9.6.<br />

This is a bugfix release. VLC media player 0.9.5 and earlier versions suffer from a security vulnerability in CUE and Realtext subtitle demuxer. Further technical details are available in <a href="http://www.videolan.org/security/sa0810.html">our advisory</a>.<br />

We recommend all users upgrade to this new version.<br />


|30 October 2008|VLC media player wins tim Award|
<img src="http://www.videolan.org/images/tim_award_2008_small.jpg" alt="tim Award" width="100" style="float:left; margin-right:5px"/>
On 30 October 2008 VLC media player won a &quot;tim Award&quot;
in category &quot;Multimedia Software&quot; at a PC-WELT event.
The awards were announced during a gala diner at &quot;Bayerische Hof&quot;
in Munich.
Two famous german TV presenters hosted the event.
The VideoLAN team is very honoured by winning this award
and wants to thank its user base for giving us this token of your appreciation.
VLC media player could not have won this award
without the support and dedication of its users and Open Source developers.

Read more about the event on <a href="http://www.pcwelt.de/start/computer/allgmein/187047/pc_welt_ehrt_top_produkte_mit_dem_tim_award/">PC-WELT</a> website.

|26 October 2008|End of support for VLC 0.8.6 series|The VideoLAN team ceases all form of support for VLC media player 0.8.6-bugfix tree.

After several several call for help,
it is apparent that there is no interest in the community
to maintain the 0.8.6 branch of the VLC media player.
As a consequence, it has not been possible to put sufficient efforts
to ensure adequate continued quality of the 0.8.6-bugfix branch.
Effective immediately,
there will be no more security and critical fixes for VLC 0.8.6.
Binary releases of the 0.8.6-bugfix branch had already stopped as of July 2008.

The VideoLAN team will continue to provide major or security-related bug fixes
for the VLC media player 0.9-bugfix branch.
If you have not already upgraded to VLC version 0.9.5, please do so urgently
(exploits for vulnerabilities found in older versions are widely available
 as of today).

|24 October 2008|VLC media player 0.9.5|The VideoLAN team is pleased to announce the release of VLC media player 0.9.5.

This is a bugfix release. VLC media player 0.9.4 and earlier versions suffer from a security vulnerability in TiVo demuxer. Further technical details are available in <a href="http://www.videolan.org/security/sa0809.html">our advisory</a> (CVE-2008-4654, CVE-2008-4686). Also, libpng was updated in Windows and MacOS builds to address a separate security issue (CVE-2008-3964).<br />

This release also improves media keys support under Windows, file access under all OSes, Qt4 interface usability, and fixes a few extra bugs. Full list of changes can be found <a href="http://www.videolan.org/developers/vlc/NEWS">here</a>.<br />

We utmostly recommend all users upgrade to this new version.<br />

Binary packages for <a href="http://www.videolan.org/vlc/download-macosx.html">Mac OS X</a> and <a href="http://www.videolan.org/vlc/download-sources.html">source code tarballs</a> are available for download. Windows binary release is indefinitely postponed pending volunteers taking over the Windows port.<br />

Help is available, as usual, in many places:
</p>
<ul class="bullets"><li>The <a href="http://wiki.videolan.org/Documentation:Documentation/">documentation</a> (we need help keeping it up to date!)</li><li>The <a href=" http://forum.videolan.org">forums</a></li><li>The <a href="http://www.videolan.org/support/lists.html">mailing lists</a></li><li>IRC: #videolan on Freenode</li></ul>

<p>We'd like to thank all our contributors, testers and users around the world for their support and help making this release possible.

|9 October 2008|A problem with Mac OS X PPC 0.9.4 binary|We accidently released the 0.9.3 Mac OS X PowerPC binary as the 0.9.4 download. We apologize for this, and corrected PowerPC and Universal downloads have been uploaded to our main mirror. It will take up to a day for these binaries to be distributed to some of our mirrors. If you want you can download the file <a href="http://download.videolan.org/pub/videolan/vlc/0.9.4/macosx/vlc-0.9.4-powerpc.dmg">directly from our main server</a>.

|7 October 2008|VLC media player 0.9.4 and Call for Windows developers|We present you with VLC media player 0.9.4, the latest increment of our 0.9 series. This release brings Windows users all the 0.9.3 enhancements and fixes (please see our call for Windows developers below) as well as fixing a few more bugs for the other platforms.
</p>
<p>Binary packages for <a href="vlc/download-macosx.html">Mac OS X</a> and <a href="vlc/download-windows.html">Windows</a>, as well as source code tarballs are available for download.<br /> Help is available, as usual, in many places:
</p>
<ul class="bullets"><li>The <a href="http://wiki.videolan.org/Documentation:Documentation/">documentation</a> (we need help keeping it up to date!)</li><li>The <a href=" http://forum.videolan.org">forums</a></li><li>The <a href="http://www.videolan.org/support/lists.html">mailing lists</a></li><li>IRC: #videolan on Freenode</li></ul>
<p>We'd like to thank all our contributors, testers and users around the world for their support and help making this release possible.<br /><br />We are putting out a call for NEW Windows developers. At the moment, our Windows-port is sorely missing some much needed love from a true Windows developer. Our team has been without a Windows developer for several months now, which is blocking us from supporting our largest usergroup in the manner we want to. We are therefore looking for developers to help our team in the areas of debugging crashes, Direct X, A/V capturing, ActiveX and Windows integration, so we can hopefully resume supporting our largest group of users in the best possible way. If we are unable to find new developers, new versions of VLC media player for Windows might become less frequent and severely out of sync with the Linux and Mac OS X versions.<br /><br />
So, no donations for work on the Windows-port and no "opportunities"-emails, for Windows we only require: Developers, Developers, Developers !!!!!

|29 september 2008|VLMa 0.2.0 release|The VideoLAN team is pleased to announce the release of VLMa (VideoLAN Manager) 0.2.0.<br />
<a href="http://www.videolan.org/vlma/download.html">Binary packages as well as source tarballs</a> are available for download.<br />
Changes from 0.1 to 0.2.0 include:
</p>
<ul>
<li>support of HTTP streaming,</li>
<li>ability to choose the encapsulation format</li>
<li>notifications of servers' accessibility using mail or IM (MSN and IRC),</li>
<li>enhanced configurability.</li>
</ul>
<p>A more complete changelog since 0.1 is available at <a href="http://www.videolan.org/vlma/NEWS">http://www.videolan.org/vlma/NEWS</a>.<br />
For more information about VideoLAN Manager, we recommend you visit <a href="http://www.videolan.org/vlma">VLMa website</a>.

|26 September 2008|VLC media player 0.9.3 and Call for Windows developers|On the heels of 0.9.2 the VideoLAN team presents version 0.9.3, the first bugfix release of the 0.9 series. We are also putting a call out for new Windows developers for our team.<br />
Binary packages for <a href="vlc/download-macosx.html">Mac OS X</a> and source code tarballs are available for download. Windows binaries might follow at a later time.<br /> Help is available, as usual, in many places:
</p>
<ul class="bullets">
<li>The <a href="http://wiki.videolan.org/Documentation:Documentation/">documentation</a> (we need help keeping it up to date!)</li>
<li>The <a href=" http://forum.videolan.org">forums</a></li>
<li>The <a href="http://www.videolan.org/support/lists.html">mailing lists</a></li>
<li>IRC: #videolan on Freenode</li></ul>
<p>
We'd like to thank all our contributors, testers and users around the world for their support and help making this release possible.<br /><br />
We are putting out a call for NEW Windows developers. At the moment, our Windows-port is sorely missing some much needed love from a true Windows developer. Our team has been without a Windows developer for several months now, which is blocking us from supporting our largest usergroup in the manner we want to. We are therefore looking for developers to help our team in the areas of debugging crashes, Direct X, A/V capturing, ActiveX and Windows integration, so we can hopefully resume supporting our largest group of users in the best possible way. If we are unable to find new developers, new versions of VLC media player for Windows might become less frequent and severely out of sync with the Linux and Mac OS X versions.<br /><br />
So, no donations for work on the Windows-port and no "opportunities"-emails, for Windows we only require: Developers, Developers, Developers !!!!!

|21 September 2008|VLC Skin Editor 0.7 release|The VideoLAN Team is pleased to announce the release of VLC Skin Editor 0.7.<br/>
After more than a year of development finally the first official stable release is there.<br/><br/>
The Skin Editor enables designers to create skins for VLC without having them to  learn about XML and the internal makeup of skins2.
It provides an easy-to-use WYIWYG editing interface giving full control over all of the skin's features.<br/><br/>
Binary packages for windows, including an installer can be found at <a href="vlc/skineditor.php">the Skin Editor page</a>.
There can also be found a build for all other operating systems for which exist a Java Runtime Environment 6 SE.<br/><br/>
We'd like to thank all contributors and testers for having made this release possible.

|17 September 2008|VLC media player at IBC 2008|<a href="http://www.ibc.org">IBC 2008</a> is the 2nd largest conference and exhibition on Broadcasting technology in the world. Though VLC media player does not have a stand (terribly expensive), it is used on many stands by the attending companies. As every year, several of the VLC media player developers were present on the floor and Derk-Jan Hartman made a <a href="http://picasaweb.google.com/d.j.hartman/IBC2008#">photo report</a> showing some of the uses, by companies like: HP, Cisco, Anystream, Fraunhofer, BBC and many smaller companies.<br />
It is the industries 'dirty little secret' you could say. Much of the IPTV based work starts by testing the IPTV streams with VLC media player. New features are sometimes even implemented in VLC media player for internal development, and then once it works, the engineers write a new program based on their experiences, which they deliver to their customers. However sometimes VLC media player even makes it into the endproduct. Big name HP clearly <a href="http://picasaweb.google.com/d.j.hartman/IBC2008#5246709674847748114">uses VLC media player in this product of theirs</a>. 


|15 September 2008|VLC media player 0.9.2 Grishenko release| The VideoLAN Team is pleased to announce the release of VLC media player 0.9.2 - Grishenko.<br />
Resulting of 2 years of development, it features many new functionalities, including a new interface for Windows and Linux.<br />
A <a href="http://wiki.videolan.org/What_is_cool_in_0.9"> comprehensive list of new features</a> can be found on our <a href="http://wiki.videolan.org/">our wiki</a> or by reading the <a href="http://www.videolan.org/developers/vlc/NEWS">release notes</a>.<br />
Binary packages for <a href="vlc/download-windows.html">Windows</a> and <a href="vlc/download-macosx">Mac OS X</a>, as well as source code tarballs are available for download.<br />
Help is available, as usual, in many places:
</p>
<ul class="bullets"><li>The <a href="http://wiki.videolan.org/Documentation:Documentation/">documentation</a> (we need help keeping it up to date!)</li><li>The <a href=" http://forum.videolan.org">forums</a></li><li>The <a href="http://www.videolan.org/support/lists.html">mailing lists</a></li><li>IRC: #videolan on Freenode</li></ul>
<p>We'd like to thank all our contributors, testers and users around the world for their support and help making this release possible.

|30 August 2008| VideoLAN Security Advisory 0807 | VLC media player versions 0.8.6i and older suffer from multiple buffer overflow vulnerabilities. <a href="http://www.videolan.org/sa0807.html">Refer to our advisory</a> for technical details. Fixes for these issues are available in VLC 0.9. We strongly recommend all users to update to this new version.<br/><b>Note:</b> a binary VLC 0.9 release should be available for Windows and Mac OS X users in a few days.

|28 August 2008|Wikileaks claims leaked DTS threat letter| In the middle of the <a href="http://www.wikileaks.org/">Wikileaks</a> controversy over the selling of claimed Hugo Chavez emails, we found out that Wikileaks claims to have uncovered <a href="http://wikileaks.org/wiki/DTS_threatens_ECP_university_over_videolan">a threat letter from DTS Inc to the ECP university</a>, our former and historical home. This letter was not addressed to the VideoLAN project. We are unable to confirm or infirm the authenticity of this document, or to comment on it at this point in time.

|12 July 2008|VLC media player 0.8.6i release|We are pleased to announce the release of VLC media player 0.8.6i.<br />This is a bugfix release. VLC media player 0.8.6h and earlier versions suffer from security vulnerabilities in the WAV demuxer.<br />This release also includes improved audio visualizations on FreeBSD and miscellaneous bug fixes in multiple modules.<br />More information can be found in our <a href="security/sa0806.html">Security Advisory</a> and in the <a href="http://wiki.videolan.org/Changelog/0.8.6i">Release Notes</a>.<br />We strongly recommend all users to update to this new version.

|6 June 2008|VLC media player 0.8.6h release|We are pleased to announce the release of VLC media player 0.8.6h.<br />This is a bugfix release. VLC media player 0.8.6g (a source code release) and earlier versions suffer from security vulnerabilities in the GnuTLS, libgcrypt and libxml2 libraries.<br />VLC media player 0.8.6f and earlier versions suffer from security vulnerabilities in the Mozilla and ActiveX plugins, in the libpng, libid3tag, libvorbis libraries and in the Speex codec.<br />
Technical details are available in our <a href="http://www.videolan.org/security/">security advisories</a>. This update also includes reliability improvements in multiple modules. More information can be found in the release notes for <a href="http://wiki.videolan.org/Changelog/0.8.6g">0.8.6g</a> and <a href="http://wiki.videolan.org/Changelog/0.8.6h">0.8.6h</a>.<br/>
We strongly recommend all users to update to this new version.

|13 May 2008|VLMa release|The VideoLAN team is pleased to announce the release of VideoLAN Manager 0.1.<br />VideoLAN Manager (VLMa) is a Java application which aims to provide an easy way to manage several servers running VLC to stream over a multicast network.<br />More information at <a href="http://www.videolan.org/vlma">http://www.videolan.org/vlma</a>.

|21 April 2008| Google Summer of Code 2008 (2)|The VideoLAN project was assigned 14 slots by Google. 10 of those went to VLC related projects and 4 to x264 projects. <a href="http://code.google.com/soc/2008/videolan/about.html">Official results</a> are available on Google's website. Thanks to all the students who posted an application. Sorry to those who weren't chosen ... and start coding if you were!

|2 April 2008|VLC media player 0.8.6f release|We are pleased to announce the release of VLC media player 0.8.6f.<br />This is a bugfix release. VLC media player 0.8.6e and earlier versions suffer from security vulnerabilities in the Subtitle demuxer, Real RTSP demuxer, MP4 demuxer and Cinepak codec.<br />This release also includes improved video output on multi-screen setups running Mac OS X and compatibility with Windows 9x/ME has been restored.<br />We strongly recommend all users to update to this new version.<br />More information can be found in our <a href="security/sa0803.html">Security Advisory</a> and in the <a href="http://wiki.videolan.org/Changelog/0.8.6f">Release Notes</a>.

|20 March 2008| Google Summer of Code 2008|As some of you might have noticed, VideoLAN has been accepted as an official mentoring organisation for <a href="http://code.google.com/soc/2008">Google's 2008 edition of Summer of Code</a>. Official student applications will be begin on the 24th and will last until the 31th. Students can apply for <a href="http://wiki.videolan.org/SoC_2008">VLC related projects</a> and <a href="http://wiki.videolan.org/SoC_x264">x264 related projects</a>. Feel free to drop by on IRC or e-mail the vlc-devel@ mailing list if you have any questions.<br/><b>Update:</b> The application deadline has been extended to the 7th of April by the Google folks.

|27 February 2008| VLC media player 0.8.6e, VideoLAN Security 0801 and 0802|
This is a bugfix release. VLC media player 0.8.6d and earlier versions suffer from security vulnerabilities in the Web interface, Subtitle demuxer, Real RTSP demuxer, SDL_image library and MP4 demuxer.<br /> Technical details are available in our advisories: <a href="http://www.videolan.org/security/sa0801.html">SA-0801</a> and <a href="http://www.videolan.org/security/sa0802.html">SA-0802</a>.<br /> The usual collection of assorted changes and improvements can be found <a href="http://wiki.videolan.org/Changelog/0.8.6e">here</a>.<br /> This release fully supports Mac OS X 10.3.9 once again. <br />We <b>strongly</b> recommend all users to update to this new version.

|30 November 2007|VLC media player 0.8.6d, VideoLAN Security Advisory 0703 | VLC media player versions 0.8.6 to 0.8.6c suffer from a security vulnerability in the ActiveX plugin. More technical details are available in our <a href="http://www.videolan.org/sa0703.html">advisory</a>.<br /> An updated release of VLC is available which includes a few other fixes as well, notably better compatibility with MacOSX 10.5 Leopard. The full list of changes can be found <a href="http://wiki.videolan.org/Changelog/0.8.6d">here</a>.<br />We strongly recommend all users to update to this new version.<br /> Note that early and broken Win32 binaries have been distributed by third party websites. Make sure to download from an official VideoLAN mirror to avoid disappointment.

|29 September 2007| VLC to remain under GPL version 2 | Future versions of VLC media player as published by VideoLAN.org will be licensed under GPL version 2 inspite of the newly released GPL version 3. See the press release <a href="/pr2007-1.html">here</a>.

|25 June 2007| Updated Mac OS X packages for VLC 0.8.6c | The previous VLC 0.8.6c binaries for Mac OS X fail to run on non-administrator accounts due to a packaging problem.<br />If you need to run VLC on restricted accounts, please download the package again. There is no security issue involved and no other platform was affected.<br />Sorry for the disturbance.

|17 June 2007|VLC media player 0.8.6c, VideoLAN Security Advisory 0702 | VLC media player versions 0.8.6b and lower suffer from a security vulnerability in the CDDA, Vorbis, Theora and SAP plugins. More technical details are available in our <a href="http://www.videolan.org/sa0702.html">advisory</a>.<br /> An updated release of VLC is available which includes a few other fixes as well.
The full list of changes can be found <a href="http://wiki.videolan.org/Changelog/0.8.6c">here</a>.<br />We strongly recommend all users to update to this
new version.

|13 June 2007| VideoLAN won a Lutèce d'or | VideoLAN was awarded a Lutèce d'Or during the latest <a href="http://www.paris-libre.org/">Paris Capitale du Libre</a> event, a technology event aimed to recognize achievements in open source development.<br /> VideoLAN received "The best Free Software development" prize for VLC media player, one year after the <a href="http://www.mozilla.org">Mozilla Foundation</a> received it for <a href="http://www.mozilla.org/firefox">Firefox</a>.

|24 April 2007| Windows Binaries for VLC 0.8.6b updated | The VLC 0.8.6b Windows binaries seemed to have a few problems with Unicode support and H.264 encoding.<br /> These issues have been fixed on our main FTP and our mirrors will follow soon.<br /> Sorry for the disturbance.

|19 April 2007| Release VLC 0.8.6b media player | From the feedback we have had so far on the latest version of VLC media player, 0.8.6a, we are proud to introduce a new bugfix release, namely 0.8.6b, aimed at fixing some annoying bugs. But with a few improvements too. <br /> It includes a new teletext subtitles decoder, new flash video decoders and Mac OS X interface improvements. It fixes many crashes, especially during fullscreen on Mac OS X, on Vista and the browser plugin.<br />
Have a look <a href="http://wiki.videolan.org/Changelog/0.8.6b">here</a> for the full list of changes.<br />We hope you will enjoy that new version.

|12 April 2007| Google Summer of Code 2007 (2)| The official applications, selected by VideoLAN and Google, are on <a href="http://code.google.com/soc/videolan/about.html">Google Summer of Code Website</a>. We have been given 7 slots for 46 applications. The choice was very hard, since many students submitted very high quality propositions. We thanks every student, accepted or not, for their application. We wish good luck to all our selected students.

|15 March 2007| Google Summer of Code 2007| VideoLAN has been accepted as an official Mentoring organisation for <a href="http://code.google.com/soc">Google Summer of Code 2007</a>. We are therefore proposing to the students eligible to that program to join us. You will have to register on Google before 24 March 2007 and propose applications to our project. You can find VideoLAN's ideas on  <a href="http://wiki.videolan.org/SoC_2007">VideoLAN's wiki</a>. Note that you can also propose new ideas.

|4 January 2007| VideoLAN Security Advisory 0701, VLC media player 0.8.6a | VLC media player versions 0.7.0 to 0.8.6 suffer from a Format String security vulnerability in the CDDA and VCDX modules. <a href="http://www.videolan.org/sa0701.html">Refer to our advisory</a> for technical details. An updated release of VLC is available now, which also improves the Fullscreen Controller on Mac OS X. We strongly recommend all users to update to this new version.

|10 December 2006| Release VLC 0.8.6 media player | Building on feedback from the 29 million downloads of VLC media player 0.8.5, we bring you version 0.8.6 with many bugfixes, as well as a couple of new features we think you will truly enjoy. Most prominent are probably Windows Media Video 9 and Flash Video. Other important changes are improved H.264 decoding, better Windows Unicode support, a Fullscreen controller and Apple Remote support for Mac OS X. <br /><b>Note: </b>If you have problems running the Mac OS X Intel version, please download again.<br />
Have a look <a href="http://developers.videolan.org/vlc/NEWS">here</a> for the full list of changes.<br />
Binary packages and the source code are available on the <a href="/vlc/">
VLC download page</a>.<br />
You can get help concerning this new release on the <a href="http://wiki.videolan.org/Documentation:Documentation/">Documentation Page</a>, <a href="http://forum.videolan.org/">Forum</a>, <a href="http://wiki.videolan.org" >Wiki</a>, <a
href="/support/lists.html" >Mailing Lists</a> or in #videolan on Freenode. 
Remember to reset your preferences if you experience problems
after upgrading from a previous version.

|29 August 2006| New MacIntel server| The builds for Mac OS X Intel were still being produced on a Development Kit Intel machine from Apple. It's time to bring that machine back to Apple and as a replacement the VideoLAN team has used the donations of our users in order to purchase a new server. The original idea was to get a MacMini, but in the configuration we wanted it, we could just as well get an iMac. Which is what we did. We <a href="http://sidekick.student.utwente.nl/gallery/album01/DSC00244?full=1">received</a> the machine last week, and now it's <a href="http://sidekick.student.utwente.nl/gallery/album01/DSC00245?full=1">setup</a>, and <a href="http://buildbot.videolan.org">keeping an eye</a> on VLC for MacIntel. We would like to thank all the people who made <a href="http://www.videolan.org/contribute.html">donations</a> very much. You people keep the project running. 

|22 August 2006| Website redesign contest: we have a winner!| We'd first like to thank the <a href="http://wiki.videolan.org/WebsiteDesign">13 web designers</a>. All the designs were great and we really had a hard time choosing a winner. So here it comes: the winner is ... &lt;drums&gt; ... <a href="http://j0nzj.deviantart.com">j0nzj</a>'s design, congratulations! We'd especially like to thank <a href="http://www.tombigel.com">Tombigel</a> who was runner up with <a href="http://wiki.videolan.org/WebsiteDesign#Tombigel">another great design</a>.

|19 June 2006|VideoLAN needs your help|There are many things that we would like to improve in VLC, but that we don't, because we simply don't have enough time. That's why we are currently looking for some help. We have identified several small projects that prospective developers could work on.<br />
Knowledge of C and/or C++ programming will certainly be useful, but you don't need to be an expert, nor a video expert. Existing VLC developers will be able to help you on these projects. You can find the list and some instructions on <a href="http://wiki.videolan.org/Mini_Projects">the dedicated Wiki page</a>. Don't hesitate to join us on <a href="http://www.videolan.org/support/">IRC</a> or on the <a href="http://www.videolan.org/support/lists.html">mailing-lists</a>. We are waiting for you ! 

|25 May 2006| Website redesign contest| Those of you browsing the web with text only console browsers might think that <a href="http://www.videolan.org">this website's design</a> is great, all the others wouldn't agree (some might even dare compare it with VLC's default interface on windows and linux). We've thus decided to give you the opportunity to change it.<br/>
Rules are available on the <a href="http://wiki.videolan.org/WebsiteRedesign">wiki</a>. All discussion and posts relative to the contest will be made in the <a href="http://forum.videolan.org/viewforum.php?f=10">Website discussion forum</a>.<br/>
<b>Update:</b> The deadline for this contest is set to Friday 14/07. You can have a look at current proposals on <a href="http://wiki.videolan.org/WebsiteDesign">this wiki page</a>.

|6 May 2006| Release: VLC media player 0.8.5 | This new Release features many improvements, including MacIntel support, a statistic system, the support of DV inputs on Linux, improvements in the Audio CD playback (CDDB), many new and improved video filters, a new AJAX HTTP interface, Winamp 2 Skins support, a Mozilla plugin on Mac OS X (PowerPC only), a new default skin...<br />
Have a look <a href="http://developers.videolan.org/vlc/NEWS">here</a>
for the full list of changes.<br />
Binary packages and the source code are available on the <a href="/vlc/">
VLC download page</a>.<br />
You can get help concerning this new release on the <a href="http://wiki.videolan.org/Documentation:Documentation/"
>Documentation Page</a>, <a href="http://forum.videolan.org/"
>Forum</a>, <a href="http://wiki.videolan.org" >Wiki</a>, <a
href="/support/lists.html" >Mailing Lists</a> or on #videolan on
Freenode. Remember to reset your preferences if you experience problems
after upgrading from a previous version.


|1 April 2006| Apple-VideoLAN partnership announced, Mac VLC to be Intel only (April fool's) | In an effort to help Apple with its Intel transition, the VideoLAN team, distributor of the industry leading cross-platform media player VLC, announced its intent to drop support for the now outdated G4 and G5 based series of Mac computers.<br />
 Read the full <a href="/pr2006-2.html">Press Release</a>.<br/>
<span style="color:red;"><b>Note:</b> Look at the date...</span>

|9 March 2006| VideoLAN website gets a new home | VideoLAN's main
server, Ganesh, will be moving to a new home at the French ISP Free. To
learn more about this move, you can read our <a
href="/pr2006-1.html">Press Release</a>.<br />
During the move, several
VideoLAN services will be down: forum, trac, SVN, and developers
website. The move should last about 4 hours, starting at 3 PM, Paris
Time. We apologize for any inconvenience.<br/>
<b>Update:</b> The server is now at its new home. Enjoy :)

|25-26 Feb 2006| VideoLAN at FOSDEM | The VideoLAN team will have a
booth at <a href="http://www.fosdem.org/2006">FOSDEM</a> in Brussels. If
you have some time to spare, drop by and we'll be happy to welcome you
on our booth.

|13 December 2005| Bugfix release: VLC media player 0.8.4a| This minor
update to VLC 0.8.4 fixes a few annoying bugs. OSX S/PDIF has been fixed
(thanks to the donations we got for the G5), and so has A/52 over S/PDIF
in Linux ALSA.<br />
MusePack is also now enabled in Windows version. Have a look
<a href="http://developers.videolan.org/vlc/NEWS">here</a> for the full
list of changes.<br />
Binary packages and the source code are available on the <a href="/vlc/">
VLC download page</a>. We have at least updated the BeOS package.<br />
You can get help concerning this new release on the <a href="http://wiki.videolan.org/Documentation:Documentation/"
>Documentation Page</a>, <a href="http://forum.videolan.org/"
>Forum</a>, <a href="http://wiki.videolan.org" >Wiki</a>, <a
href="/support/lists.html" >Mailing Lists</a> or on #videolan on
Freenode. Remember to reset your preferences if you experience problems
after upgrading from a previous version.


|26 November 2005| Release: VLC media player 0.8.4| This new release
features many improvements including a new VLC cone, new Mac OS X
wizard and extend controls dialogs, tree playlist skins2 support, HTTP
interface CGI handling, linux binary codecs loader, UPnP and Bonjour
service discovery, shoutcast stream forwarding, new languages ...<br />
Have a look <a href="http://developers.videolan.org/vlc/NEWS">here</a>
for the full list of changes.<br />
Binary packages and the source code are available on the <a href="/vlc/">
VLC download page</a>.<br />
You can get help concerning this new release on the <a href="http://wiki.videolan.org/Documentation:Documentation/"
>Documentation Page</a>, <a href="http://forum.videolan.org/"
>Forum</a>, <a href="http://wiki.videolan.org" >Wiki</a>, <a
href="/support/lists.html" >Mailing Lists</a> or on #videolan on
Freenode. Remember to reset your preferences if you experience problems
after upgrading from a previous version.

|17 November 2005| Purchase of a Powermac G5| Thanks to the numerous contributions we received from everywhere,
we were finally able to buy a second hand dual G5 1.8 GHz.<br />
This will be used to debug sound playback on Powermacs and to host the VLC nightly builds. We particularly wish to thank <a href="http://www.macbidouille.com/">MacBidouille</a> and <a href="http://www.avosmac.com/">à Vos Macs</a> for their important support.

|15 October 2005| Release: miniSAPserver 0.3.2| This release cumulates fixes for regressions introduced in 0.3.1. You are encouraged to upgrade to this new version: <a href="/streaming/download-sap-server.html">download it here</a>.

|11 October 2005| 10 million downloads for VLC 0.8.2| VLC 0.8.2 has been downloaded ten million times since its release, on June 26th! The whole VideoLAN team is very happy of this overwhelming result. We would like to thank all of our users, sponsors and partners, who made this result possible. Stay tuned !

|19 September 2005| New nightly builds server| The new nightly build server is now available at <a href="http://nightlies.videolan.org/">http://nightlies.videolan.org</a>. We would like to thank French ISP <a href="http://www.free.fr">Free</a> for their generous donation of this Dell PowerEdge 1425 server (2 2.8GHz Xeon EMT64 CPUs, 1.5 GB RAM and 2 x 40 GB Hard drives ... which we upgraded to 2 x 250 GB).<br/><b>Update 22 September:</b> The nightly builds are back !

|4 September 2005| Announcing Planet VideoLAN| <a href="http://planet.videolan.org">Planet VideoLAN</a> (which uses the <a href="http://www.planetplanet.org/">Planet Planet</a> software) is an aggregation of VideoLAN-related posts on VideoLAN developers blogs. The best source for fresh VideoLAN news, previews and insights ! We currently have 3 feeds, but hope to have several more very soon.

|2 September 2005| Donations for the G5| Due to a bit of media attention
on various websites, we have had a surge in donations the past 2 days.
Almost 1,5 times our original target of EUR 900 has been donated.
 So finally we can afford to get us that
G5 PowerMac that we needed. Perhaps there will even be some money left.
Don't worry, we will spent the money very wisely, we promise. There is still
lots of other hardware we would like to support one day. And of course we
have our usual server, conference representation and ADC costs. So please
keep <a href="contribute.html">being kind to us</a> and other Free and Open Source
Software projects around the world. We thank you very much. 

|9 July 2005| Release: miniSAPserver 0.3.0| This release allows proper
announcing of RTP streams, performs characters set convertion
automatically when needed, selects the most appropriate SAP multicast
address automatically and supports manual output interface selection.
Some minor issues were fixed. These updates are in adequacy with
changes in version 0.8.2 of VLC media player.
You are encouraged to upgrade to this version:
<a href="/streaming/download-sap-server.html">
download it here</a>.

|26 June 2005| Release: VLC media player 0.8.2| This new release features many
imporvements including a full playlist rewrite, improved preferences,
Mac OS X Tiger compatibility, a brand new Internet Explorer ActiveX
plugin, a port to Pocket PC, mosaic picture in picture system, easy
snapshots ...<br />
Have a look <a href="http://developers.videolan.org/vlc/NEWS">here</a>
for the full list of changes.<br />
Binary packages and the source code are available on the <a href="/vlc/">
VLC download page</a>.<br />
You can get help concerning this new release on the <a href="http://wiki.videolan.org/Documentation:Documentation/"
>Documentation Page</a>, <a href="http://forum.videolan.org/"
>Forum</a>, <a href="http://wiki.videolan.org" >Wiki</a>, <a
href="/support/lists.html" >Mailing Lists</a> or on #videolan on
Freenode. Remember to reset your preferences if you experience problems
after upgrading from a previous version.

|16 June 2005| VideoLAN at LinuxTag| The VideoLAN team will be present at <a href="http://www.linuxtag.org/">LinuxTag</a> in Karlsruhe, Germany the 23 and 24 of June 2005. We will also hold a conference on VLC.

|13 June 2005| Server Downtime| Due to a rack installation, some VideoLAN services will be down for some time today around midnight (CEST). The main website, forum, SVN and trac will be down during that time. Sorry for the inconvenience

|31 May 2005| New HP webserver| The VideoLAN website is now running on a HP DL 385 server with two AMD opteron 2.4 GHz CPUs and 8 GB RAM. The developers, forum, trac and wiki websites will be moved to this new server shortly. The VideoLAN team would like to thank Jean-Marie Verdun from HP France for this nice donation. It will hopefully fix the many problems we've been having durring the last year concerning website avaibility. (Photos of the new webserver will be uploaded shortly)

|27 May 2005| VideoLAN wins award at Trophées du Libre| The VideoLAN team won the first prize in the « Multimedia » category at international free software contest <a href="http://www.tropheesdulibre.org">Trophées du Libre</a> (<a href="http://www.tropheesdulibre.org/article.php3?id_article=47">awards list</a>). We thus got a brand new HP laptop and a nice trophy. The laptop is already making friends in the cone community (<a href="http://download.videolan.org/images/sirius1.png">cones watching</a> <a href="http://download.videolan.org/images/sirius2.png">Roland Garros</a>).

|26 May 2005| VideoLAN T-Shirts now available| VideoLAN T-Shirts are now available for download on <a href="/goodies.html">the goodies page</a> ! Thanks to Lorenzo Milito for the winning design. Use a standard inkjet printer to get one ... You can also get one if you donate 12 EUR or 16 USD to the VideoLAN project. More info is available on <a href="/goodies.html">the goodies page</a>.

|14-15 May 2005| Linux Cambrésis| The VideoLAN team will be present at <a href="http://linuxcambresis.org/">Linux Cambrésis</a> in Northen France. We will also hold conferences on Saturday and Sunday.

|27 April 2005| Network Downtime| Due to a network upgrade, some VideoLAN services will be down for some time today around noon (CEST). The main website and downloads will keep working, but forum, wiki, SVN and mailing lists will be down during that time. Sorry for the inconvenience

|1 April 2005| Release: VLC 0.8.1337 (April Fool's)| Lots of new features have found their way into VLC ! VLC is now easy to use and bug free. ( see <a href="http://download.videolan.org/pub/videolan/vlc/0.8.1337/changelog.txt"> Full Change Log</a> ) Hurry up and download the new version here : [ links removed ]
Screenshots can be found <a href="http://download.videolan.org/pub/videolan/vlc/0.8.1337/vlc-l33t.jpg">here</a> (linux) and <a href="http://download.videolan.org/pub/videolan/vlc/0.8.1337/vlc-l33t-win.jpg">here</a> (windows) and <a href="http://download.videolan.org/pub/videolan/vlc/0.8.1337/vlc-0.8.1337-macosx.png">here</a> (macosx).<br />
<b>NOTE:</b> Look at the posting date before downloading this version. <b>This is an April Fool's Joke.</b>


|24 March 2005| Journées Federez| The VIA and VideoLAN teams are
pleased to invite you to their annual presentation day at the
Ecole Centrale Paris (châtenay-Malabry, France). This year's
edition is organised with networking associations from more than
a dozen French engineering schools and universities. There will
be a presentation of VideoLAN in French at 9:00 a.m. and a small
demonstration from 13:30 to 15:30. If you are interested, please visit
<a href="http://federez.net/journees/">http://federez.net/journees/</a>.

|26-27 Feb 2005| VideoLAN at FOSDEM | The VideoLAN team will have a
booth at <a href="http://www.fosdem.org/2005">FOSDEM</a> in Brussels. A
small presentation of VideoLAN will be held by Zorglub. If you happen
to be near Brussels this week end, we'll be happy to welcome you on our
booth.<br />
<b>Update: </b>Read the report <a href="/events">here</a>.

|15 Feb 2005| VideoLAN at Solutions Linux Paris | You have been many to
come at the CNIT, Paris La Defense to meet the VideoLAN team. We want to
thank you for your multiples usages of VLC media player and all your
ideas of future developement. Our hardware were partialy lent by
<a href="http://www.apple.com">Apple</a> and help we to tests new
features. Photos can be found
<a href="/events/20050201/index.html">here</a>.

|7 Feb 2005| VideoLAN T-shirt design contest | The VideoLAN team is
about to make its very first T-shirts in world history ! Unfortunately,
we lack any good design proposal. Hence, we'd like to ask all of our
users with some drawing skills to come up with design proposals. The
winning design will of course be used on millions of T-shirts ! (and the
author might even get one for free ...)<br />
<a href="http://wiki.videolan.org/T-Shirt_Design_Contest">Some more info here</a><br />
<b>Update: </b>Submissions are closed

|1-3 Feb 2005| VideoLAN at Solutions Linux Paris | VideoLAN will have
a booth at <a href="http://www.solutionslinux.fr/en/">Solutions Linux
Paris 2005</a>, which will take place at the CNIT, Paris La Defense. The
VideoLAN team will welcome you at the booth.

|23 January 2005| New: VLC Streaming HOWTO| VLC's documentation rewrite
is finished ! The <a href="/doc">complete user guide for the server
aspects of VLC</a> is now available.

|19 January 2005| The VideoLAN project investigates possible
violation of their intellectual property| See the press release
<a href="/pr2005-1.html">here</a>. <span
style="font-weight: bold;">Update :</span> Following our request, Cinema
On Web has removed the download from their web site. We would like to
thank them for their quick response.

|12 December 2004| New: VLC Play HOWTO| VLC's documentation
rewrite is nearing completion. We are proud to bring you the <a
href="http://wiki.videolan.org/Documentation:Documentation/">VLC Play HOWTO</a>, a complete guide
to VLC's use as a client. Translations and the VLC streaming HOWTO will
follow shortly.

|4 December 2004| Scheduled downtime| VideoLAN's main website will be
down for several hours on December 4th 2004, between 13:00 and 17:00 GMT,
because of a major work at our power supplier. Subversion source code
repositories, online forums, mailing lists, their archives and email
accounts will also be affected by the cut.<br />Sorry for the
inconvenience.

|15 November 2004| Release: VLC 0.8.1| This is mainly a bug fix release.<br />
Look <a href="http://developers.videolan.org/vlc/NEWS">here</a> for the
list of changes. To download the sources or the binary package of this
new version, go to the <a href="/vlc/">VLC
download page</a> and click on your OS logo!<br /> Only source, Win32
and Mac OS X package are available at the moment, others should follow
soon.<br />

|3 November 2004| Release: VLC 0.8.0| It has been a long wait, but it is finally there.
A plethora of new features for everyones enjoyment. They include:
faster and more flexible input layer, improved transcoding, a plugins cache
to speedup VLC startup time, vastly improved subtitles, OSD and DVD support,
Windows Media Video 3 support under Windows, Multipart JPEG webcam support,
an audio equalizer and so much, much more.<br />
Look <a href="http://developers.videolan.org/vlc/NEWS">here</a> for a complete
list of changes. To download the sources or the binary package of this
new version, go to the <a href="/vlc/">VLC
download page</a> and click on your OS logo!<br /> Only source, Win32
and Mac OS X package are available at the moment, others will follow
soon.<br />
<b>NOTE:</b> This release doesn't include DTS audio decoding support.
DTS Inc. claims that distributing this software with DTS decoding capabilities is a violation of their patent EP 864 146. At DTS Inc. request, we decided, as a precautionary measure, to provisionally suspend the distribution of VLC with DTS decoding capabilities while reviewing DTS Inc. claim. This is not an acknowledgement of the validity of the claim.


|23 October 2004| Server upgrade| We will be upgrading our Web server
today. A few minutes downtime will occur near 13:00 GMT.
Sorry for the inconvenience.

|23 July 2004| Release: miniSAPserver 0.2.4| This release fixes a 
major problem with miniSAPserver where it was always announcing mp3
streams instead of mpeg-ts (vls produced) streams. It also fixes the
playlistgroup parameter to be compliant with the SDP standard now.
The new style of this parameter will be supported in the next 
version of VLC. We strongly advise all users of miniSAPserver to 
<a href="/streaming/download-sap-server.html">
download</a> and upgrade to this new version.

|21 May 2004| Release: VLC 0.7.2| This new release of VLC media
player features improved interfaces with support for embedded
video outputs, new formats support (H261, CMML, H264, Theora
alpha3, ...), an improved DVB input, subtitles improvements, major
stream output improvements, a VideoLAN manager to manage several
streams with only one instance of VLC, and much more. Look <a
href="http://developers.videolan.org/vlc/NEWS">here</a> for a complete
list of changes. To download the sources or the binary package of this
new version, go to the <a href="/vlc/">VLC
download page</a> and click on your OS logo!<br /> Only source, Win32
and MacOS X package are available at the moment, others will follow 
soon.


|8 April 2004| VIA and VideoLAN annual presentation day| The VIA
and VideoLAN teams are pleased to invite you to their annual
presentation day at the Ecole Centrale Paris (Châtenay-Malabry,
France). There will be a presentation of VideoLAN in French at
10:45 a.m. with a full demonstration. If you are interested, please
visit <a href="http://www.via.ecp.fr/via/journeevia2004.html">this
page</a>. To receive an invitation, send a mail to <a
href="mailto:journee2004@via.ecp.fr">journee2004@via.ecp.fr</a>.


|3-4 April 2004| VideoLAN at HackIT:04| We will
participate to the italian hackmeeting in Genova (see <a
href="http://www.hackmeeting.org/">http://www.hackmeeting.org/</a>). We
will hold a conference about video streaming and make demos on saturday
and sunday.

|1 April 2004| Previews of next release | The new version of VLC is
coming up, and we thought we'd show you some pictures of the stuff
we have been working on. First of all VLC will now be able to play
all <a href="http://download.videolan.org/images/real.jpg">Real</a>
and <a href="http://download.videolan.org/images/wmv3.jpg">Windows
Media Video 3</a> content. A <a
href="http://download.videolan.org/images/vlc-os9.png">Mac
OS 9</a> version is now available as well, and
there is a new plugin to stream video to the <a
href="http://members.tripod.com/~annie43/spa/sp29.gif">Spirit
Marsrover</a>.<br />
<b>NOTE: </b>Look at the posting date before asking stupid questions.

|18 March 2004| Scheduled downtime| Due to maintainance operations, 
a network downtime of about one hour will occur this day at about 
12AM. Sorry for the inconvenience.

|7 March 2004| VideoLAN Wiki back | After a long time down, the VideoLAN
wiki (ie, a website that everyone can change) is back up, at
<a href="http://wiki.videolan.org">http://wiki.videolan.org</a>. Its
goal is to document what is not in the official documentation: the tips
for each O.S, the graphical interfaces, ... We hope that the
contribution of VideoLAN users will help us keep a documentation
as up-to-date as possible.

|2 Mar 2004| Release: VLC 0.7.1| This new release of VLC media
player is a bit more than a bug-fix release as it does in fact include many
new features. IGMPv3 support (Linux and WinXP), software DTS audio decoding,
MOD audio support, a few new demuxers, an OpenGL video output plugin for OSX
and much more! Look <a href="http://developers.videolan.org/vlc/NEWS">here</a>
for a complete list of changes.
To download the sources or the binary package of this new version,
go to the <a href="http://www.videolan.org/vlc/">VLC download page</a>
and click on your OS logo!<br />
<b>Note:</b> A 0.7.1a release is now available for Mac OS X users that fixes
two important bugs in the 0.7.1 release.

|16 Feb 2004| Release: VLS 0.5.6| This release of VLS fixes
a bug when streaming MPEG2/PS files with several AC3 tracks,
as well as compilation of VLS on Mac OS X. Go to the <a
href="http://www.videolan.org/streaming/download-vls-sources.html">VLS
source code download page</a> to get this new version now !

|10 Feb 2004| VLC supports DTS audio | The latest
<a href="http://download.videolan.org/pub/videolan/testing/vlc-0.7.1-test1/">
test release</a> of <a href="http://www.videolan.org/vlc/">VLC media player</a>
comes with DTS audio support. Try it out!

|10 Feb 2004| First release of dtsdec |
<a href="http://www.videolan.org/dtsdec.html">dtsdec</a> is a free
DTS Coherent Acoustics decoder. DTS is a high quality multi-channel (5.1)
digital audio format in use in DVD's and DTS audio CD's. The code for dtsdec
is still in early development stage, but it is already quite useable.<br />
<a href="http://www.videolan.org/vlc/">VLC media player</a> becomes the
first Open Source application able to play DTS audio.

|3-5 Feb 2004| VideoLAN at Solutions Linux Paris | VideoLAN will have
a booth at <a href="http://www.solutionslinux.fr/en/">Solutions Linux
Paris 2004</a>, which will take place at the CNIT, Paris La Defense. The
VideoLAN team will welcome you at the booth and invites you to its
conference about reverse engineering and interoperability
(February 3rd afternoon).

|17 Jan 2004| OSI Merit Award| The VideoLAN project is very proud
to announce that it has been awarded with an Open Source Merit Award
by the <a href="http://www.opensource.org">Open Source
Initiative</a>. We are very glad to be honored in this
way and will continue to strive to making the project, VLC media player
and VLS, the best programs out there.<br />
You can read more about the award in these <a href="http://builder.com.com"
>builder.com</a> articles: <a href="http://builder.com.com/5100-6375-5136758.html">
article 1</a> <a href="http://builder.com.com/5100-6375-5136135.html">
article 2</a>.

|10 Jan 2004| Release: VLS 0.5.5| This release of VLS fixes a bug
introduced in the DVB input of the previous release. Go to the <a
href="http://www.videolan.org/streaming/download-vls-sources.html">VLS
source code download page</a> to get this new version now !

|3 Jan 2004| Release: VLC 0.7.0| This major release of VLC Media
Player, codenamed "Bond", features major core enhancements, support
for RTP/RTSP, new audio visual effects, supports for new formats
(Speex, MPEG2 4/2/2, AAC+SBR, ...), many interfaces and playlist
enhancements, a new interface for MacOS X, a DirectShowinput on
Win32, support for MacOS X 10.3 Panther, and much more! Look <a
href="http://developers.videolan.org/vlc/NEWS">here</a> for a complete
list of changes. To download the sources or the binary package of this
new version, go to the <a href="http://www.videolan.org/vlc/">VLC
download page</a> and click on your OS logo!<br />
<b>Attention: </b>The first version of the OS X package didn't include
the Flac decoder. If you experience problems with Flac audio, please
download again.

|2 Jan 2004| Release: libdvbpsi 0.1.4| This new release of libdvbpsi 
fixes a few bugs and adds support for DVB subtitles descriptor.

|1 Jan 2004| Happy new year| The VideoLAN team wishes you a happy new
year !

|29-30 Dec 2003| Scheduled downtime| Due to a power audit, major
disruptions are expected. A rescue line will be set up during the
downtime, but due to a very narrow bandwidth, only the main website 
will be (partially) up. Sorry for the inconvenience.

|13 Dec 2003| Release: miniSAPserver 0.2.3| This new release
fixes an IPv6 bug, adds support for HTTP streams and for the
SLP announcing protocol. It also uses the recent playlist group
system of VLC (requires CVS or beta version of VLC). You can <a
href="http://www.videolan.org/streaming/download-sap-server.html">download
 the sources</a> for this release.

|28 Nov 2003| Release: VLS 0.5.4 | This new release
of the VideoLAN Server fixes two major bugs:
the "program_number don't match" bug (read <a
href="http://www.via.ecp.fr/via/ml/vls-devel/200311/msg00012.html">this</a>
for more explanations about this fix) and a bug in the RTP
option that made VLS consume unnecessary resources. Go to the <a
href="http://www.videolan.org/streaming/download-vls-sources.html">VLS
source code download page</a> to get this new version now !

|23 Nov 2003| New web forum for VideoLAN| The VideoLAN team
is pleased to announce the opening of our new webforum (<a
href="http://forum.videolan.org">http://forum.videolan.org</a>). We hope
this will help improve user support, communication between VideoLAN
users, and sharing of ideas. Have fun !

|31 Oct - 1 Nov 2003| 5th Free software days in Lyons| VideoLAN
will be present at the 5th Free Software (<i>Journées du Libre</i>)
in Lyons, France. We will have a demo of the streaming solution
on our booth ! For more information about the event, see the <a
href="http://www.aldil.org/agenda/journees/2003/">ALDIL web site</a>.

|20 Oct 2003| VideoLAN doc switches to GPL| Due to legal problems with
the GNU FDL license, the VideoLAN doc was switched to General Public
License. The VideoLAN Quickstart was also removed, as it was redundant
with the VideoLAN Howto.

|20 Sept 2003| VLC awarded by MacGeneration| During Apple Expo
Paris 2003, VLC won the trophy for developers support ! For more
details about the MacGeneration 2003 Trophies, please see <a
href="http://www.macgeneration.com/mgnews/depeche.php?aIdDepeche=103478"
>this news</a> (French, see <a href="http://babelfish.altavista.com/babelfish/urlload?url=http%3A%2F%2Fwww.macgeneration.com%2Fmgnews%2Fdepeche.php%3FaIdDepeche%3D103478">BabelFish</a> for an English translation).

|14 Aug 2003| Release: VLC 0.6.2| This new release of VLC follows
the previous one very closely because it mainly fixes a regression in
VLC 0.6.1 which made some streams unplayable. VLC 0.6.2 also features
an improved MPEG TS muxer, proper PTS/DTS generation in the transcoding
module, support for DVB-S/C/T cards using V4L2 API, DVD menus navigation
in the wxWindows interface and fixes to the VCD navigation. Look <a
href="http://developers.videolan.org/vlc/NEWS">here</a> for a complete
list of changes. To download the sources or the binary packages of
this new version, go to the <a href="http://www.videolan.org/vlc/">VLC
download page</a> and click on your OS logo!

|31 July 2003| Release: VLC 0.6.1| This new release of VLC media
player features: vorbis and mp3 audio support for the transcoding
module, improved HTTP remote control interface, improved support
for the Matroska container format, new subtitle module which
uses freetype2 to render arbitrary fonts in any size, improved
PS muxer (it can create MPEG-1 files now and produce streams
with system headers), Windows fixes (DVD support, 5.1 audio for
sblive/audigy and sound on NT4), improved ALSA support and a new
GTK2 interface for the "Linux on PDA" distributions! Look <a
href="http://developers.videolan.org/vlc/NEWS">here</a> for a complete
list of changes. To download the sources or the binary packages of
this new version, go to the <a href="http://www.videolan.org/vlc/">VLC
download page</a> and click on your OS logo! WARNING: the first version
of the Mac OS X package was broken... so if you have problems under Mac
OS X, download the package again!

|29 July 2003| Release: libdvdcss 1.2.8 and libdvbpsi 0.1.3| Libdvdcss
1.2.8 is a bug-fix release with a fix for encrypted DVDs on Windows
and a workaround for strange discs that report read errors seemingly
at random. Libdvbpsi 0.1.3 features new DVB descriptors decoders and
generators, a new SDT decoder and various fixes and enhancements. Go to
the <a href="http://developers.videolan.org/libdvdcss/">libdvdcss</a>
and <a href="http://developers.videolan.org/libdvbpsi/">libdvbpsi</a>
web pages to read the Changelog and download the sources or the Debian
packages.

|25 July 2003| Release: miniSAPserver 0.2.2| Minor bug fix of the
miniSAPserver. Remember miniSAPserver should be used to announce the
streams sent by VLS; the streams sent by VLC's stream output can be
announced by VLC itself !

|25 June 2003| VLC runner up for Apple Design Award| VLC 0.5.3 is
runner up for Apple Design Award 2003. You can see the trophy on the
<a href="/events/">events page</a>.

|23 June 2003| Release: VLC 0.6.0| This major release of VLC
media player features a new Video 4 Linux input, a new CDDA
input, multicast IPv6 support under Windows and Mac OS X, support
for Sorenson 3, a new HTTP remote control interface, improved
wxWindows and skin interfaces (now available for X11), a new stream
output scheme with transcoding support and much more! Look <a
href="http://developers.videolan.org/vlc/NEWS">here</a> for a complete
list of changes. To download the sources or the binary packages of
this new version, go to the <a href="http://www.videolan.org/vlc/">VLC
download page</a> and click on your OS logo!

|23 June 2003| Release: Libdvdcss 1.2.7| This new release of
libdvdcss, a DVD decryption library used by VLC and many other GPL media
players, has key caching enabled by default and some bugfixes. See the <a
href="http://developers.videolan.org/libdvdcss/">libdvdcss page</a> to
download the sources or the Debian packages.

|20 June 2003| Release: miniSAPserver 0.2.1| This new version of the
miniSAPserver offers IPv6 support both for announces and announced
streams, together with the CVS version of VLC.

|16 June 2003| VideoLAN Wiki opened | We have set up a Wiki 
(ie, a website that everyone can change) at 
<a href="http://wiki.videolan.org">http://wiki.videolan.org</a>. Its 
goal is to document what is not in the official documentation: the tips
for each O.S, the graphical interfaces, ... We hope that the 
contribution of VideoLAN users will help us keep a documentation 
as up-to-date as possible.

|11-13 June 2003| Renater IPv6 conference| The VideoLAN team has a booth
at the <a href="http://www.renater.fr/IPv6-2003Caen/index.htm">Renater
IPv6 conference</a> that takes place at the University of Caen
(France). There is a running demo of IPv6 streaming with VideoLAN in
unicast and multicast at the booth!

|10 June 2003| Documentation update | The VLS user guide is back and
we have a Spanish translation of the VideoLAN FAQ by Javier Varela
: see the <a href="http://wiki.videolan.org/Documentation:Documentation/">documentation page</a>. All the VideoLAN
documentation is now in Docbook XML.

|6 June 2003| Release: VLS 0.5.3 | This release fixes a bug in the
command line parsing, adds DVD title and chapter selection with the
configuration file and features a new Windows installer.

|29 May 2003| Hauppauge WinTV-PVR-250 supported | We have managed to
stream from a Hauppauge WinTV-PVR-250 (an MPEG-2 encoding card) under
Linux ! It gives much better results than the Visiontech Kfir card. The
chapter "Stream from an MPEG encoding card" of the VideoLAN HOWTO has
been updated, see the <a href="http://wiki.videolan.org/Documentation:Documentation/">documentation page</a>.

|26 May 2003| Release: mini-SAP-server 0.2.0 | This new release of the
mini-SAP-server produces packets that should be conform to the RFC and
adds a "port" option. Only the CVS version of VLC accepts its announces.

|25 May 2003| VLC FAQ becomes VideoLAN FAQ | The new VideoLAN FAQ is
available in multiple formats on the <a href="http://wiki.videolan.org/Documentation:Documentation/">documentation
page</a>. If you have remarks about it or would like new questions to be
integrated in it, post in one of the user mailing-lists.

|23 May 2003| VLC nominated at the Free Software
Trophies! | VLC was nominated at the <a
href="http://www.tropheesdulibre.org/main.php?lang=en">Free Software
Trophies</a>, an international competition aimed at promoting the
development of free software, in the category "General Public".

|21 May 2003| Release: VLS 0.5.2 | This release fixes a bug when
trying to stream multiple DVB channels and a bug in the configure
script with DVB drivers. To download this new version, go to the <a
href="http://www.videolan.org/streaming/">streaming page</a>.

|16 May 2003| Release: VLS 0.5.1 | VLS for Windows is back ! The Windows
port of VLS has been fixed. This new version also features the loop
on broken PS files and setting the TTL under Windows. To download the
sources or the Windows executable of this new version, go to the <a
href="http://www.videolan.org/streaming/">streaming page</a>.

|26 Apr 2003| New VideoLAN HOWTO | The new VideoLAN HOWTO is now
complete and up-to-date. The chapter about the channel information
service now explains how to do SAP/SDP announces with the new <a
href="/streaming/download-sap-server.html">mini-SAP-server</a>. See the
<a href="http://wiki.videolan.org/Documentation:Documentation/">documentation page</a> and report any problem to the
<a href="/support/lists.html">user mailing-lists</a>.

|8 Apr 2003| Release: VLC 0.5.3 | This new release features the
first steps towards skinable interfaces (only on Windows, not
yet on Mac OS X or *nix). Support for playing directories and
video4linux are other big new features. Many bugs have been fixed,
including the problem with USB speakers on MacOS X. Look <a
href="http://developers.videolan.org/vlc/NEWS">here</a> for a complete
list of changes. To download the sources or the binary packages of
this new version, go to the <a href="http://www.videolan.org/vlc/">VLC
download page</a> and click on your OS logo!

|8 Apr 2003| New skin for the Web site | Karibu has designed a new skin
for the Web site : enjoy !

|21 Mar 2003| VIA and VideoLAN annual presentation day| The VIA
and VideoLAN teams are pleased to invite you to their annual
presentation day at the Ecole Centrale Paris (Châtenay-Malabry,
France). There will be a presentation of VideoLAN in French at
10:45 a.m. with a full demonstration. If you are interested, please
visit <a href="http://www.via.ecp.fr/via/journeevia2003.html">this
page</a>. To receive an invitation, send a mail to <a
href="mailto:journee2003@via.ecp.fr">journee2003@via.ecp.fr</a>.

|11 Mar 2003| Release: VLC 0.5.2 | This new release features
improved audio quality (especially under Mac OS X), support for
new audio formats (audio DV and FLAC), support for streaming of
DivX 1/2/3, WMV 1/2 and h/i263 with VLC's stream output and many
bug fixes (including the lock-ups under Mac OS X). To download the
sources or the binary packages of this new version, go to the <a
href="http://www.videolan.org/vlc/">VLC download page</a> and click on
your OS logo!

|11 Mar 2003| Release: VLS 0.5.0 | This major release features a
new command line interface, support for the new LinuxTV drivers
(which brings support for the streaming of digital terrestial
television channels), MPEG-4 TS support and many bug fixes. Because
of a well hidden bug, VLS is not available under Windows any
more. To download the sources of this new version, go to the <a
href="http://www.videolan.org/streaming/">streaming page</a>.

|10 Mar 2003| Release: libdvdcss 1.2.6 | This is a bug
fix release of libdvdcss, a DVD decryption library used
by VLC and many other GPL media players. See the <a
href="http://developers.videolan.org/libdvdcss/">libdvdcss page</a> to
download the sources or the binaires.

|10 Mar 2003| Release: libdvdplay 1.0.1 | This is a bug fix release
of libdvdplay, a DVD navigation library used by VLC. See the <a
href="http://developers.videolan.org/libdvdplay/">libdvdplay page</a> to
download the sources or the binaires.

|26 Feb 2003| Release: vlc for YOPY| The VideoLAN team is proud
to announce that vlc now works on YOPY/Linupy based PDAs !
Please have a look at the <a href="/vlc/download-linupy.html">
download page</a>.

|18 Feb 2003| Release: vlc 0.5.1a for Mac OS X | This is a bug-fix
release of VLC for Mac OS X only: It fixes the problem with 
VLC starting up in a different language than your preferred 
language and an issue with sound missing on several files
that previously worked perfectly. Download the new version of VLC 
for Mac OS X <a href="/vlc/download-macosx.html">here</a>.

|17 Feb 2003| Release: vlc 0.5.1 | This is a bug-fix
release of VLC with a few new features : see the <a
href="http://developers.videolan.org/vlc/NEWS">list of changes between
0.5.0 and 0.5.1</a> and go to the <a href="/vlc/">VLC section</a>
of the website to download the binaries for your OS or the sources.
Unfortunately, this release doesn't fix the audio problems under Mac OS
X... but VideoLAN developers are working hard on it !

|3 Feb 2003| Release: vlc 0.5.0 | This is a major release
of VLC with a a lot of great new features : see the <a
href="http://developers.videolan.org/vlc/NEWS">list of changes between
0.4.6 and 0.5.0</a> and go to the <a href="/vlc/">VLC section</a>
of the website to download the binaries for your OS or the sources.
A new VLC user guide has been released (it replaces the VLC HOWTO)
and the VideoLAN Quickstart has been updated to explain the new
streaming capacity of VLC (with VLC's new stream output) : see the <a
href="http://wiki.videolan.org/Documentation:Documentation/">documentation page</a>.

|3 Feb 2003| Release: libdvdplay 1.0.0 | This is the first release
of libdvdplay, a DVD navigation library. This library is based on a
lot of Ogle's code and features basic read and seek for DVD media,
export of the DVD information (audio, subtitles, chapters, ...) and
export of the DVD virtual machine to the client application. See the <a
href="http://developers.videolan.org/libdvdplay/">libdvdplay page</a> to
download the sources or the binaires.

|3 Feb 2003| Release: libdvdcss 1.2.5 | This new libdvdcss release
adds key cache support, improves robustness in case of read errors
and builds under Cygwin and Microsoft Visual C++. See the <a
href="http://developers.videolan.org/libdvdcss/">libdvdcss page</a> to
download the sources or the binaires.

|29 Jan 2003| VideoLAN at Linux Expo Paris | VideoLAN will have a booth
at <a href="http://www.linuxsolutions.fr">Linux Expo Paris 2003</a>
(4-5-6 February 2003 at the CNIT). The VideoLAN team will welcome you at
the booth and invites you to its <a href="http://www.linuxsolutions.fr/EN/home/index.php?site=conferences_programme">conference</a> (Conference n°5, February
5th afternoon).

|19 Jan 2003| New VideoLAN Quickstart | The VideoLAN Quickstart has been
completely rewritten. See the <a href="http://wiki.videolan.org/Documentation:Documentation/">documentation page</a>.

|19 Jan 2003| New web site | Welcome to our new web site:
it was designed to be simpler and more comprehensive for
end-users. There is a separate site for developers: <a
href="http://developers.videolan.org/">developers.videolan.org</a>.
If you find errors, please write to <a
href="mailto:webmaster@videolan.org">webmaster@videolan.org</a>.

|14 Nov 2002| Release: vlc 0.4.6 | This new release uses a52dec as the
default decoder for AC3 sound for a better quality, fixes a hangup in
the esd plugin, allows Windows NT/2000/XP users to read DVDs without
administrator privileges and fixes a few segfaults. Have a look at
the <a href="/vlc/changelog.html">ChangeLog</a> and go to the <a
href="/vlc/download.html">download page</a>.

|14 Nov 2002| Release: libdvdcss 1.2.4 | This release
allows Windows NT/2000/XP users to watch DVDs with vlc
0.4.6 without administrator privileges. Check the <a
href="/libdvdcss/index.html">libdvdcss</a> page, and have a look at the
<a href="http://videolan.org/libdvdcss/changelog.html">Changelog</a>.

|4 Nov 2002| Pictures and slides of JDL Lyons | The pictures and the
slides of the Free Software Days in Lyons are online: see the <a
href="/events/">events page</a>.

|1-2 Nov 2002| Free Software days in Lyons | VideoLAN will be
present at the Free Software Days (<i>Journées du Libre</i>) in Lyons
(France): four developers will have a stand with a running demo of
VideoLAN. This event is organized by ALDIL, and you will have all the
information about the stands, the conferences and a site map on <a
href="http://www.aldil.org/agenda/journees/2002/">this page</a>.

|14 Oct 2002| Release: vlc 0.4.5 | This new release brings enhancements to
the BeOS and iPAQ familiar Linux ports, as well as a new RTP input. VLC
is also compliant to general practice on how to embed A/52, DVD SPU and
LPCM elementary streams in MPEG-2 TS. It can still read from VLS 0.3.x
with the --vls-backwards-compat option.
Visit the <a href="/vlc/changelog.html">ChangeLog</a> and the <a
href="/vlc/download.html">download page</a>.

|13 Oct 2002| Release: mini-vlcs 0.2.0 | This new release adds
IPv6 support, features unlimited channel numbers and auto-reload
when the configuration file is changed. Get-it from the <a
href="/network/download.html">download page</a>!

|13 Oct 2002| Release: vls 0.4.0 | This new release adds IPv6 multicast
support, language descriptors for audio and subpicture streams, and
support for WinTV DVB-S. It also features an RTP output, runtime adding
of programs and channels, start-up script,
and is compliant to general practice on how
to embed A/52, DVD SPU and LPCM elementary streams. This release
requires VLC version 0.4.5 or later. Get it now from the
<a href="/vls/download.html">download page</a>!

|13 Oct 2002| Release: libdvdcss 1.2.3 | This release fixes many issues
in the Windows port. Check the
<a href="/libdvdcss/index.html">libdvdcss</a> page, and have a look at the <a href="http://videolan.org/libdvdcss/changelog.html">Changelog</a>.

|13 Oct 2002| Release: vlms 0.2.3 | VLMS now generates valid CRCs, and is
compliant to general practice on how to embed A/52, DVD SPU and LPCM elementary
streams. This release requires VLC version 0.4.5 or later.
<a href="/vlms/download.html">Download it now</a>.

|12 Oct 2002| Release: libdvbpsi 0.1.2 | This release fixes miscellaneous
portability issues, and a bug in the PMT generator which created
over-complicated PMTs. Check the
<a href="/libdvbpsi/index.html">libdvbpsi</a> page, and have a look at the <a href="http://videolan.org/libdvbpsi/changelog.html">Changelog</a>.

|11 Aug 2002| Release: vlc 0.4.4 | This release fixes some Windows
bugs and is built on the newest libdvdcss. It also features ffmpeg
AVIs playing. Subtitles should be readable again under MacOS X.
Visit the <a href="/vlc/changelog.html">ChangeLog</a> and the <a
href="/vlc/download.html">download page</a>.

|11 Aug 2002| Release: libdvdcss 1.2.2 | This release fixes the
"ioctl_ReadTitleKey failed" bug reported by RPC2 drives users. Check the
<a href="/libdvdcss/index.html">libdvdcss</a> page, and have a look at the <a href="http://videolan.org/libdvdcss/changelog.html">Changelog</a>.

|26 Jul 2002| Release: vlc 0.4.3 | This release <b>fixes the
QT6 compatibility issue</b> under MacOS X! Also includes a few
BeOS improvements, and several other bugfixes. Visit the <a
href="/vlc/changelog.html">ChangeLog</a> and the <a
href="/vlc/download.html">download page</a>.

|10 Jul 2002| Release: vlc 0.4.2 | This is a small bugfix release, but
also features multicast IPv6 support and new deinterlacing plugins. See
the <a href="/vlc/changelog.html">ChangeLog</a> and the <a
href="/vlc/download.html">download page</a>.

|4 Jun 2002| Release: vlc 0.4.1 | This is mostly a bugfix release
with a few improvements. Support for AVI files with AC3 audio, new
MMX optimizations in the video decoder an improved Win32 interface,
and a lot of other bugfixes. See
full <a href="/vlc/changelog.html">ChangeLog</a> for more
information. Then go to the <a href="/vlc/download.html">download
page</a>.

|4 Jun 2002| Release: vlms 0.2.2 | vlms works
under MacOSX and Solaris and not only under Linux.
Now the playlist and looping options work with TS files.
<a href="/vlms/download.html">Download it now</a>

|2 Jun 2002| Release: libdvdcss 1.2.1 | This release fixes
a bug preventing to read DVDs when the disc's region didn't
match the drive's. Also, QNX support was added. Check the <a
href="/libdvdcss/index.html">libdvdcss</a> page.

|29 May 2002| Tests at Centrale Paris| The VideoLAN Team is
starting today a vast test campaign on the campus of the <a
href="http://www.ecp.fr">Ecole Centrale Paris</a>. We are streaming
13 channels at the same time using multicast on the brand new
network (Gigabit Ethernet backbone and 100 Mbit/s switches on
the periphery from our partner <a href="partners.html">Extreme
Networks</a>) of the <a href="http://www.via.ecp.fr">VIA Centrale
Réseaux</a> association. The students are invited to visit <a
href="tests/">www.videolan.org/tests/</a> for instructions.

|23 May 2002| Release: vlc 0.4.0 | This is a major release which
adds MPEG-4/DivX support and many enhancements for Mac OS X and Windows.
It also fixes dozens of causes of crashes and freezes. See
full <a href="/vlc/changelog.html">ChangeLog</a> for more
information. Then go to the <a href="/vlc/download.html">download
page</a>.

|23 May 2002| Release: libdvdcss 1.2.0 | This release
fixed a grave crash with some DVDs. Check the <a
href="/libdvdcss/index.html">libdvdcss</a> page!

|18 May 2002| Release: libdvbpsi 0.1.1 | This release has full MPEG 2
descriptors decoding and generation capabilities. Get it now from the
<a href="/libdvbpsi/download.html">download page</a>.

|14 May 2002| VideoLAN HOWTO| The <a
href="network/doc/videolan-howto.html">VideoLAN HOWTO</a> explains
how to use the complete VideoLAN solution. It deals in particular
with the different streaming methods (unicast, broadcast,
multicast), the issue of IPv6, the use of channel tools, Video on
Demand and the design of a complete solution. It has been written
by <a href="mailto:marcari@videolan.org">Marc Ariberti</a> and <a
href="mailto:alexis@videolan.org">Alexis de Lattre</a>.

|14 May 2002| Release: vlms 0.2.1| This release adds a few
convenient options. It is now possible to change the TTL value
and to make the vlms repeat its playlist.

|13 may 2002| Release: vls 0.3.3 | This new release adds a long
awaited Windows port for the vls! Get it now from the
<a href="/vls/download.html">download page</a>!

|23 apr 2002| Thinkpad received | We eventually received the
IBM Thinkpad as a reward for the IBM Linux Challenge. See
the <a href="events/index.html">events page</a> and the <a
href="events/20020423/index.html">pictures</a> taken during the
unpacking party.

|18 apr 2002| New vlc HOWTO | <a href="mailto:jobi@videolan.org">Jobi</a>
updated the <a href="vlc/doc/vlc-howto.html">vlc HOWTO</a>. It is an
important document for all the users of vlc.

|18 apr 2002| Release: vlc 0.3.1 | This is a bugfix release which
addresses issues discovered in 0.3.0. Lots of crashes fixed, see the
full <a href="/vlc/changelog.html">ChangeLog</a> for more
information. Then go to the <a href="/vlc/download.html">download
page</a>.

|15 apr 2002| Mirror Site | You probably experienced problems
recently to access the VideoLAN Web, FTP and CVS servers. This
was due to failure of the ISP. We have set up a mirror site with
Web; FTP and read-only CVS. When the ISP of the main site is
down, you will be automatically redirected to the mirror site.

|6 apr 2002| VideoLAN Quickstart | The <a
href="/doc/videolan-quickstart/videolan-quickstart.html">VideoLAN
Quickstart</a> describes how to start using VideoLAN quickly.
Basic skills on Linux and Network should be enough to understand
this Quickstart. It has been written by Bill Eldridge (<a
href="mailto:bill@rfa.org">bill@rfa.org</a>) and Alexis de Lattre
(<a href="mailto:alexis@videolan.org">alexis@videolan.org</a>).

|6 apr 2002| Release: vlc 0.3.0 | This release fixes an amazing number
of bugs and brings a lot of new features as well: Configuration
file support, new input layer with IPv6 support and file format
autodetection, new video output engine featuring speed increases
up to 40%, VCD support under Mac OS X, multicast support and a
new interface for Win32, network support under BeOS, satellite
driver for WinTV Nova cards, video filters (deinterlacing,
rotation, distort, image wall) and much more! Read the <a
href="/vlc/changelog.html">ChangeLog</a> and go to the <a
href="/vlc/download.html">vlc download page</a>.

|6 apr 2002| Release: libdvdcss 1.1.1 | This bugfix release fixes
compilation issues under OpenBSD, IRIX and BeOS. You do not need to
upgrade if 1.1.0 worked properly for you. Otherwise, check the <a
href="/libdvdcss/index.html">libdvdcss</a> page!

|4 apr 2002| Release: vls 0.3.2 | Major update, a lot of new features
since 0.3.1: WinTV-Nova satellite receiver support, IPv6 support,
multicast improvement, user documentation and lots of bugfixes.
See <a href="/vls/changelog.html">changelog</a> and <a
href="/vls/download.html">download</a> pages.

|4 apr 2002| Release: libdvdcss 1.1.0 | This new release of the
most portable DVD descrambler is a lot more robust, includes a
new descrambling method, is now in sync with the Ogle group's own
version, features an HP-UX port, and fixes many bugs. Check the <a
href="/libdvdcss/index.html">libdvdcss</a> page for more information.

|3 apr 2002| Release: libdvbpsi 0.1.0 | This is the first official
release of libdvbpsi. It features PAT and PMT decoding and generation.
It is used by vls under Linux but the code is fully portable. Check the
<a href="/libdvbpsi/index.html">libdvbpsi</a> page for more information.

|25 mar 2002| Release: miniVLCS 0.1.2 | Small update, configuration file is now
a lot more simple to write but it can only support the newest vlc network syntax
(udp://). See the <a href="/network">network page</a> for more information and
download.

|5 mar 2002| Meuuh got his Ti!

|jan 2002| Linux Challenge: VideoLAN wins | Videolan is one of
the 25 winners of the IBM Linux Challenge for opensource projects
developed by university students. More information on the <a
href="http://www-1.ibm.com/linux/news/ilsc.shtml"> IBM Linux
Challenge</a> website.

|31 dec 2001| Release: vlc 0.2.92 | This release fixes an amazing number
of bugs, provides a new optimized buffer manager, fast memcpy routines,
MacOS X network input, BeOS CPU detection, DVD raw device support, a new
libmad audio decoder, and a new aRts audio output. Read the <a
href="/vlc/changelog.html">ChangeLog</a>
or go to the <a href="/vlc/download.html">download</a> page.

|6 dec 2001| Release: vls 0.3.1 | Major update, a lot of new features
since 0.3.0: Kfir video encoder support, plugins, file output, bugfixes.
See <a href="/vls/changelog.html">changelog</a> and <a
 href="/vls/download.html">download</a> pages.

|13 nov 2001| Release: vlc 0.2.91 | A bug-fix update,
with numerous fixes in the Win32 and MacOS X port,
and VCD support for Linux and BSD/OS.
See <a href="/vlc/changelog.html">changelog</a> and <a
href="/vlc/download.html">download</a> pages.

|13 nov 2001| Release: libdvdcss 1.0.0 | MacOS X, NetBSD and OpenBSD
ports were added to this version, along with new methods for descrambling
DVDs.

|10 oct 2001| Release: vlc 0.2.90 | Another major update,
with a new improved video decoder, a working Mac OS X
port with Altivec optimized routines, HTTP input support.
See <a href="/vlc/changelog.html">changelog</a> and <a
href="/vlc/download.html">download</a> pages.

|9 oct 2001| Release: vls 0.3.0 | This is the first official release
of the VideoLAN Server. It features MPEG1 PS, MPEG2 PS/TS, and DVD
streaming, a telnet interface, and runs under Linux and Solaris. Check
the <a href="/vls/index.html">vls</a> page for more information.

|24 aug 2001| Release: vlms 0.2.0 | The first version for more than
one year. Lots of bugfixes, and support for MPEG1 streams. See the <a
href="/vlms/index.html">vlms</a> page for more information.

|22 aug 2001| Release: libdvdcss 0.0.3 | Solaris port and BSD/OS ports
were added to this version.

|22 aug 2001| Release: vlc 0.2.83 | Minor release, with overlay subtitle
support.

|7 aug 2001| Release: vlc 0.2.82 | This version fixes lots of
issues discovered in 0.2.81, but also introduces the BSD/OS
port, and a few other Win32 improvements. See the usual <a
href="/vlc/changelog.html">changelog file</a> for a more
complete report on what has changed, or directly go to the <a
href="/vlc/download.html">download page</a>!

|2 aug 2001| Connection failure | We apologize for the 24 hour downtime
due to a power audit.

|28 jul 2001| Release: vlc 0.2.81 | This version comes after a huge
bug hunt, almost all critical bugs have disappeared, and all important
ones are gone. See the <a href="/vlc/changelog.html">changelog file</a>
for more information. This is also the first public version to use
libdvdcss. <a href="/vlc/download.html">Download</a> it now!

|28 jul 2001| Release: libdvdcss 0.0.2 | This new version brings lots
of bugfixes, full Windows 98 and Windows 2000 support, and a faster DVD
key handling. Get it on the <a href="/libdvdcss/">libdvdcss</a> page.

|26 jun 2001| Server failure | We apologize for the 24 hour server
downtime, but our server's motherboard fried and we experienced
additional RAID array issues. Recovery was, erm, fun.

|19 jun 2001| Release: libdvdcss 0.0.1 | <a
href="/libdvdcss/">libdvdcss</a> is the cross-platform library used
by vlc, the VideoLAN Client, to access DVDs with transparent CSS
decryption. It is the first library based on the vlc codebase, but
others are planned.

|5 jun 2001| Release: vlc 0.2.80 | A major step to 0.3.0,
with a somewhat working <a href="/vlc/windows.html">Windows
port</a>, network support which was gone since 0.2.0, additional
MMX and 3D Now! acceleration routines, still improved DVD
support, and the usual insane amount of bug fixes. Check out
the <a href="/vlc/download.html">download</a> page, and the <a
href="/vlc/changelog.html">changelog file</a>.

|16 may 2001| VideoLAN Client API documentation | <a
href="http://www.idealx.com/">IdealX</a>, a French Open Source
company, has had former VideoLAN team member Christophe Massiot
work full time on the vlc API documentation. It is available <a
href="http://www.idealx.org/en/doc/videolan-manual/">on the IdealX Open
Source web site</a>.

|1 may 2001| Release: VLAN server 0.0.1 | The VLAN server is now
released. Go to the <a href="/vlcs/download.html">download</a> page for
more information.

|28 apr 2001| Release: vlc 0.2.73 | Release just before we
break everything before freeze :-). Some bugfixes too (QNX and
FreeBSD) and enhancements to the xvideo module. Check out the
<a href="/vlc/download.html">download</a> page, and the <a
href="/vlc/changelog.html">changelog file</a>.

|16 apr 2001| Release: vlc 0.2.72 | A quick bugfix release which
solves issues introduced in 0.2.71 (crash at startup on BeOS and
MacOS X, and a few DVDs not working). Get your copy on the <a
href="/vlc/download.html">download</a> page.

|14 apr 2001| Port-specific pages created | We did a port-specific
page for each vlc port known to work, so that you can keep
track of what is happening to your platform's port. Currently
available port pages are <a href="/vlc/beos.html">BeOS</a>, <a
href="/vlc/linux.html">Linux</a>, <a href="/vlc/macosx.html">MacOS X</a>
and <a href="/vlc/solaris.html">Solaris</a>.

|13 apr 2001| Release: vlc 0.2.71 | This is a bugfix release which fixes
most of the issues discovered in 0.2.70: no more segfaults when compiled
with gcc 3.0pre and versions of gcc shipped with the latest RedHat
distributions, fixed the BeOS CSS decryption, fixed a few issues in IFO
parsing, fixed XVideo video output, and updated icons under Linux, BeOS
and MacOS X.

|9 apr 2001| Release: vlc 0.2.70 | After a long wait, version
0.2.70 of the VideoLAN Client is out. Amongst the news, the usual
bunch of bugfixes, even better DVD support under Gnome, Gtk+ and
BeOS, with on-the-fly chapter selection, language selection, a
playlist, an early MacOS X port, XVideo support, network input. <a
href="/vlc/download.html">Download it</a>.

|5 mar 2001| Release: vlc 0.2.63 | Bugfixes, bugfixes, and bugfixes
again, a Gtk+ interface for the Gnome-impaired, an even better
DVD support, and an interface and overlay support for BeOS. <a
href="/vlc/download.html">Get it</a> now.

|1 mar 2001| CVS snapshots available | There are so many
CVS commits that we could do a daily release, so a <a
href="/pub/videolan/vlc/snapshots/">daily VLC CVS snapshot</a> has just
been set up for people who can't wait.

|21 feb 2001| Release: vlc 0.2.62, with BeOS CSS support | Lots of
bugfixes, automatic hardware acceleration with SDL, enhanced DVD
title support, return of the framebuffer, Glide and GGI plugins,
various optimizations to the AC3 decoder, and, of course, the return
of the <b>BeOS port</b> with new features like drag'n'drop and <b>CSS
decryption</b>. Go and <a href="/vlc/download.html">get it</a> while
it's still hot!

|19 feb 2001| CVSWeb interface | We now have a <a
href="/cgi-bin/cvsweb/">CVSWeb interface</a> on the site.

|16 feb 2001| Release: vlc 0.2.61 | This new bugfix version brings
plain X11 support (which was broken), enhanced CSS support, a few new
interface features including drag'n'drop support, and fixes a few
reported bugs. As usual, <a href="/vlc/download.html">download</a> it
quickly!

|15 feb 2001| Hurricane vandalizes CVS repository | Bozo
"weeeeuuuuaaaaaaaaahhhhhhhhh, toupétéééééééé" Hurricane launched today
his vls code cleaning, which means he broke everything, but also that
vls is almost ready for a release.

|14 feb 2001| Release: vlc 0.2.60 | This new unstable version brings
astounding features over the stable one, like MPEG1 support, direct DVD
support, DVD decryption, arbitrary seeking in the stream, pause, fast
forward and slow motion, hardware YUV acceleration. Get it from the <a
href="/vlc/download.html">download</a> section!

|14 feb 2001| New website | The website has been simplified a lot,
because the old one was reported as confusing. Here it is, in all its
valid XHTML glory.

|2 feb 2001| First official release! | Director of École Centrale Paris
has <a href="/images/paper.jpeg">signed</a> the authorization to release
all the VideoLAN components under the GPL.

|31 jan 2001| See the new vlc at the Linux Expo in Paris | vlc has been
forked into two branches: stable (0.2.0, codenamed Onatopp) and unstable
(0.2.50, codenamed Urumov). Unstable has a lot of new interesting
features.

|20 jan 2001| Changed web server | We have moved the web site to our
brand new IBM server. Please let us know if anything goes wrong on the
web pages.

|07 dec 2000| VideoLAN on a floppy | For our beta-tests campaign on our
local network, we have created a boot floppy allowing non-Linux users to
boot off the floppy and load the vlc through an NFS mountage. It rocks!

|06 dec 2000| New beta-test campaign! | VideoLAN is not vlc. It's a
whole network solution; we are testing again, on our LAN, as many
improvements have been done to the three part of the project ( videolan
server, vlan solution, client ) since we last tested it. We expect about
50 to 100 beta-testers. See the test section if you are a student in the
Residence of the Ecole Centrale.

|22 nov 2000| For rh7.0 users ... | Redhat 7.0 users may have
difficulties to build the vlc, as the version included in rh7.0 isn't a
stable one. We advice you either to take the rpm or to downgrade to gcc
2.95

|27 aug 2000| Release: vlc 0.1.99i | A new version of the VideoLAN
client fixes a few display bugs, we now have field images support
and the motion compensation isn't buggy any more. Check the <a
href="/vlc/download.html">download</a> section.

|23 aug 2000| Release: vlms 0.1.99h | The VideoLAN mini server has been
released! Check the <a href="/vls/download.html">download</a> section.

|22 aug 2000| Release: vlc 0.1.99h | Check the <a
href="/vlc/download.html">download</a> section, as well as the <a
href="/vlc/changelog.html">changelog file</a>.

|16 aug 2000| Release: vlc 0.1.99g | Check the <a
href="/vlc/download.html">download</a> section, as well as the <a
href="/vlc/changelog.html">changelog file</a>.

|16 aug 2000| The moron of the week: Sam | Sam wrote a buggy Makefile
which prevented code to be compiled with optimizations. Now that this
issue has been fixed, we got a 40% speed increase!

|11 aug 2000| New TODO list | We did a <a href="/vlc/todo.html">TODO
list</a> for the 0.2.0 release. People wanting to help might pick up
ideas from this list.

|8 aug 2000| Release: vlc 0.1.99f | Check the <a
href="/vlc/download.html">download</a> section, as well as the <a
href="/vlc/changelog.html">changelog file</a>.

|20 jul 2000| Release: vlc 0.1.99e | This mostly fixes an urgent fix for
BeOS, see the <a href="/vlc/download.html">download</a> section.

|12 jul 2000| Release: vlc 0.1.99d | We are the 12th and vlc 0.1.99d
was just released. Check the <a href="/vlc/download.html">download</a>
section!

|15 jun 2000| Beta tests pre-release! | The client is being pre-released
today! Though the full network solution is not available yet, it already
lets you watch your favorite DVD with Linux!

|1 jun 2000| Screenshots online | Some <a
href="/screenshots/">screenshots</a> have been put online so that people
know VideoLAN isn't vaporware :)

|29 may 2000| More beta-tests | A beta-test campaign will take place on
the VIA network this week.

|23 mar 2000| New web site announcing release | We're getting closer to
a release, and we are preparing the web site for featuring dowloads and
bug fixes.

|27 feb 2000| Added a list of unencrypted DVDs | Most DVDs are
encrypted, but some are not. To encourage this, we provide a <a
href="/freedvd.html">list</a> of known unencrypted DVDs. Any body can
tell us 'Hey, this cool DVD is unencrypted'!

|4 feb 2000| VideoLAN thanks all visitors at the Linux Expo | We would  
like to thank all the visitors who showed interest in our project at    
the Linux Expo in Paris. Pictures of our stand will soon be available.  

|28 jan 2000| VideoLAN is going OpenSource! | We got almost all the
authorizations in order to distribute the VideoLAN components under the
General Public License. Our school director still needs to sign one
paper.

|24 jan 2000| More performance increase | Our new custom video decoder
gives us a 50% speed increase. We now can play DVDs at full framerate on
a Celeron 366 using framebuffer output, which makes the vlc the fastest
available software DVD player under Linux.<br /> According to Meuuh,
there're still many improvements that can be done.

|21 jan 2000| Presentation day photos available | Some photos of
the presentation day are available on VIA's website:<br /> <a
href="http://www.via.ecp.fr/assoce/videolan-20000121/">http://www.via.ec
p.fr/assoce/videolan-20000121/</a>

|05 jan 2000| VideoLAN will be at the Linux Expo
in Paris | Come to see VIA and the VideoLAN team
at the <a href="http://www.linux-expo.com/">Linux
Expo</a> in Paris. A map can be found here: <a
href="http://www.via.ecp.fr/assoce/linuxexpo.jpeg">http://www.via.ecp.fr
/assoce/linuxexpo.jpeg</a>.

|18 dec 1999| DVD, BeOS and framebuffer support") | The videolan client
now suports the Linux framebuffer output, and has been ported to
BeOS.<br /> Moreover, the mini-server now can emit a TS stream directly
from a DVD drive.

|10 dec 1999| Presentation day | A presentation day will take place
on <b>January the 21st, 2000</b>. Everyone interested in the project
is welcome to come and see it working. <br /><b>Find out more <a
href="presentation/">here</a>!</b>

|08 dec 1999| Beta-test has begun! | A large scale beta-test period has
just begun. Several members of the VideoLAN team have started testing
the VLAN solution now that the vlanbridge works. All students of the
Ecole Centrale are welcome to test the client with us, providing <b>they
have Linux and don't mind losing the Windows network neighbourhood for
the entire duration of the beta test</b>.

|16 nov 1999| Presentation day | A presentation day will take place in
january 2000 at the Ecole Centrale, in Paris. We expect to show you our
full MPEG2 solution. Find out more when the date has been chosen.

|15 nov 1999| New website | The website has been updated. It had been
about one year since nothing had changed here (we were too busy coding
*g*). Expect to find here as much as we are allowed to give away in a
few weeks, starting from screenshots or hopefully more.

|22 oct 1999| Huge performance increase on the vlc | Thanks to Polux,
who rewrote the YUV transformation in the vlc using MMX assembly, a mere
P2-300 can now display about 12fps of MPEG2 video.

|empty entry to prevent script from mangling the last entry
